WITH
    'FormatFactorySettings.h' AS cpp_file,
    settings_from_cpp AS
    (
    SELECT extract(line, 'DECLARE\\(\\w+, (\\w+),') AS name
    FROM file(cpp_file, LineAsString)
    WHERE match(line, '^\\s*DECLARE\\(')
    ),
    setting_aliases AS
    (
        SELECT
            alias_for,
            groupArray(name) AS aliases
        FROM system.settings
        WHERE alias_for != ''
        AND alias_for IN settings_from_cpp
        GROUP BY alias_for
    ),
    main_content AS
    (
    SELECT format('## {} {} {}  \n\n{}{}\n\n{}\n\n',
    s.name,
    '{#'||s.name||'}',
    multiIf(s.tier == 'Experimental', '<ExperimentalBadge/>', s.tier == 'Beta', '<BetaBadge/>', ''),
    if(sa.aliases IS NOT NULL AND length(sa.aliases) > 0,
       '**Aliases**: ' || arrayStringConcat(arrayMap(x -> '`' || x || '`', sa.aliases), ', ') || '\n\n',
       ''),
    if(s.type != '' AND s.default != '', format('<SettingsInfoBlock type="{}" default_value="{}" />', s.type, s.default), ''),
    trim(BOTH '\\n' FROM s.description))
    FROM system.settings s
    LEFT JOIN setting_aliases sa ON s.name = sa.alias_for
    WHERE s.name IN settings_from_cpp
    ORDER BY s.name
    ),
    '' ||
'---
title: ''Format Settings''
sidebar_label: ''Format Settings''
slug: /operations/settings/formats
toc_max_heading_level: 2
description: ''Settings which control input and output formats.''
doc_type: ''reference''
---

import ExperimentalBadge from ''@theme/badges/ExperimentalBadge'';
import BetaBadge from ''@theme/badges/BetaBadge'';
import SettingsInfoBlock from ''@theme/SettingsInfoBlock/SettingsInfoBlock'';
import VersionHistory from ''@theme/VersionHistory/VersionHistory'';

<!-- Autogenerated -->
These settings are autogenerated from [source](https://github.com/ClickHouse/ClickHouse/blob/master/src/Core/FormatFactorySettings.h).

' AS prefix
SELECT prefix || (SELECT groupConcat(*) FROM main_content)
INTO OUTFILE 'settings-formats.md' TRUNCATE FORMAT LineAsString
