WITH
    main_content AS
    (
    SELECT format('## {} {} {}  \n\n{}\n\n{}\n\n',
    name,
    '{#'||name||'}',
    multiIf(tier == 'Experimental', '<ExperimentalBadge/>', tier == 'Beta', '<BetaBadge/>', ''),
    if(type != '' AND default != '', format('<SettingsInfoBlock type="{}" default_value="{}" />', type, default), ''),
    trim(BOTH '\\n' FROM description))
    FROM system.settings
    WHERE type = 'format_setting' AND is_obsolete = 0
    ORDER BY name
    ),
    '' ||
'---
title: ''Format Settings''
sidebar_label: ''Format Settings''
slug: /operations/settings/formats
toc_max_heading_level: 2
description: ''Settings which control input and output formats.''
doc_type: ''reference''
---

import ExperimentalBadge from ''@theme/badges/ExperimentalBadge'';
import BetaBadge from ''@theme/badges/BetaBadge'';
import SettingsInfoBlock from ''@theme/SettingsInfoBlock/SettingsInfoBlock'';
import VersionHistory from ''@theme/VersionHistory/VersionHistory'';

<!-- Autogenerated -->
These settings are autogenerated from system tables.

' AS prefix
SELECT prefix || (SELECT groupConcat(*) FROM main_content)
INTO OUTFILE 'settings-formats.md' TRUNCATE FORMAT LineAsString
