WITH
    settings_changes AS
    (
        SELECT
            setting_name AS name,
            '[' ||
            arrayStringConcat(
                arrayMap(
                    (i, x) -> '{' ||
                        '"id": "row-' || toString(i) || '",' ||
                        '"items": [' ||
                            '{"label": "' || toString(x.1) || '"},' ||
                            '{"label": "' || toString(x.2) || '"},' ||
                            '{"label": "' || replaceRegexpAll(x.3, '([\\"])', '\\\\$1') || '"}' ||
                        ']' ||
                    '}',
                    arrayEnumerate(groupArray((version, default_value, comment))),
                    groupArray((version, default_value, comment))
                ),
            ', '
        ) ||
        ']' AS rows
        FROM
        (
            SELECT
                (arrayJoin(changes) AS change).1 AS setting_name,
                version,
                change.3 AS default_value,
                change.4 AS comment
            FROM system.settings_changes
            WHERE type = 'Session'
            ORDER BY setting_name, version DESC
        )
        GROUP BY setting_name
    ),
    settings_with_change_history AS
    (
        SELECT
            a.*,
            b.*
        FROM
            system.settings AS a
        LEFT OUTER JOIN settings_changes as b
        ON a.name = b.name
        WHERE a.is_obsolete = 0
    ),
    main_content AS
    (
    SELECT
        format('## {}{}{}{}{}{}{}\n\n',
        name,
        ' {#'||name||'} \n\n',
        multiIf(tier == 'Experimental', '<ExperimentalBadge/>\n\n', tier == 'Beta', '<BetaBadge/>\n\n', ''),
        if(description LIKE '%Only has an effect in ClickHouse Cloud%', '<CloudOnlyBadge/>\n\n', ''),
        if(
            type != '' AND default != '',
            format(
                '\n\n<SettingsInfoBlock type="{}" default_value="{}" />\n\n',
                type,
                replaceRegexpOne(default, 'auto\(\d+\)','auto(N)')
            ),
            ''
        ),
        if(rows != '', printf('\n\n<VersionHistory rows={%s}/>\n\n', rows), ''),
        replaceOne(trim(BOTH '\\n' FROM description), ' and [MaterializedMySQL](../../engines/database-engines/materialized-mysql.md)',''))
    FROM settings_with_change_history
    ORDER BY name
    ),
'---
title: ''Session Settings''
sidebar_label: ''Session Settings''
slug: /operations/settings/settings
toc_max_heading_level: 2
description: ''Settings which are found in the ``system.settings`` table.''
doc_type: ''reference''
---

import ExperimentalBadge from \'@theme/badges/ExperimentalBadge\';
import BetaBadge from \'@theme/badges/BetaBadge\';
import CloudOnlyBadge from \'@theme/badges/CloudOnlyBadge\';
import SettingsInfoBlock from \'@theme/SettingsInfoBlock/SettingsInfoBlock\';
import VersionHistory from \'@theme/VersionHistory/VersionHistory\';

<!-- Autogenerated -->
All below settings are also available in table [system.settings](/docs/operations/system-tables/settings). These settings are autogenerated from system tables.

' AS prefix
SELECT prefix || (SELECT groupConcat(*) FROM main_content)
INTO OUTFILE 'settings.md' TRUNCATE FORMAT LineAsString
