// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion

const clickhouseTheme = require('prism-react-renderer/themes/vsLight');
//const clickhouseTheme = import('./src/theme/clickhouseTheme.mjs');

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'ClickHouse Docs',
  tagline: 'Documentation, quick starts, user guides, technical references, FAQs and more...',
  url: 'https://clickhouse.com/',
  baseUrl: '/',
  onBrokenLinks: 'error',
  onBrokenMarkdownLinks: 'ignore',
  favicon: 'img/favicon.ico',
  organizationName: 'ClickHouse', 
  projectName: 'clickhouse-docs', 
  plugins: [
    'remark-docusaurus-tabs',
    [
      require.resolve('docusaurus-lunr-search'),
      {
        excludeRoutes: [
          'docs/whats-new/changelog/**/*', // exclude changelogs from indexing
      ]
      },
    ],
    [
      '@docusaurus/plugin-client-redirects',
      {
        redirects: [
          {from: '/docs/en/development/browse_code',to: '/docs/en/development/browse-code'}, 
          {from: '/docs/en/development/build_cross_arm',to: '/docs/en/development/build-cross-arm'}, 
          {from: '/docs/en/development/build_cross_osx',to: '/docs/en/development/build-cross-osx'}, 
          {from: '/docs/en/development/build_osx',to: '/docs/en/development/build-osx'}, 
          {from: '/docs/en/development/developer_instruction',to: '/docs/en/development/developer-instruction'}, 
          {from: '/docs/en/database_engines/',to: '/docs/en/engines/database-engines/'}, 
          {from: '/docs/en/engines/database_engines/',to: '/docs/en/engines/database-engines/'}, 
          {from: '/docs/en/database_engines/lazy',to: '/docs/en/engines/database-engines/lazy'}, 
          {from: '/docs/en/engines/database_engines/lazy',to: '/docs/en/engines/database-engines/lazy'}, 
          {from: '/docs/en/database_engines/mysql',to: '/docs/en/engines/database-engines/mysql'}, 
          {from: '/docs/en/engines/database_engines/mysql',to: '/docs/en/engines/database-engines/mysql'}, 
          {from: '/docs/en/engines/table_engines/',to: '/docs/en/engines/table-engines/'}, 
          {from: '/docs/en/operations/table_engines/',to: '/docs/en/engines/table-engines/'}, 
          {from: '/docs/en/engines/table_engines/integrations/',to: '/docs/en/engines/table-engines/integrations/'}, 
          {from: '/docs/en/engines/table_engines/integrations/hdfs',to: '/docs/en/engines/table-engines/integrations/hdfs'}, 
          {from: '/docs/en/operations/table_engines/hdfs',to: '/docs/en/engines/table-engines/integrations/hdfs'}, 
          {from: '/docs/en/engines/table_engines/integrations/jdbc',to: '/docs/en/engines/table-engines/integrations/jdbc'}, 
          {from: '/docs/en/operations/table_engines/jdbc',to: '/docs/en/engines/table-engines/integrations/jdbc'}, 
          {from: '/docs/en/engines/table_engines/integrations/kafka',to: '/docs/en/engines/table-engines/integrations/kafka'}, 
          {from: '/docs/en/operations/table_engines/kafka',to: '/docs/en/engines/table-engines/integrations/kafka'}, 
          {from: '/docs/en/engines/table_engines/integrations/mysql',to: '/docs/en/engines/table-engines/integrations/mysql'}, 
          {from: '/docs/en/operations/table_engines/mysql',to: '/docs/en/engines/table-engines/integrations/mysql'}, 
          {from: '/docs/en/engines/table_engines/integrations/odbc',to: '/docs/en/engines/table-engines/integrations/odbc'}, 
          {from: '/docs/en/operations/table_engines/odbc',to: '/docs/en/engines/table-engines/integrations/odbc'}, 
          {from: '/docs/en/engines/table-engines/log-family/log-family',to: '/docs/en/engines/table-engines/log-family/'}, 
          {from: '/docs/en/engines/table_engines/log_family/',to: '/docs/en/engines/table-engines/log-family/'}, 
          {from: '/docs/en/engines/table_engines/log_family/log',to: '/docs/en/engines/table-engines/log-family/log'}, 
          {from: '/docs/en/operations/table_engines/log',to: '/docs/en/engines/table-engines/log-family/log'}, 
          {from: '/docs/en/engines/table_engines/log_family/stripelog',to: '/docs/en/engines/table-engines/log-family/stripelog'}, 
          {from: '/docs/en/operations/table_engines/stripelog',to: '/docs/en/engines/table-engines/log-family/stripelog'}, 
          {from: '/docs/en/engines/table_engines/log_family/tinylog',to: '/docs/en/engines/table-engines/log-family/tinylog'}, 
          {from: '/docs/en/operations/table_engines/tinylog',to: '/docs/en/engines/table-engines/log-family/tinylog'}, 
          {from: '/docs/en/engines/table_engines/mergetree_family/',to: '/docs/en/engines/table-engines/mergetree-family/'}, 
          {from: '/docs/en/engines/table_engines/mergetree_family/aggregatingmergetree',to: '/docs/en/engines/table-engines/mergetree-family/aggregatingmergetree'}, 
          {from: '/docs/en/operations/table_engines/aggregatingmergetree',to: '/docs/en/engines/table-engines/mergetree-family/aggregatingmergetree'}, 
          {from: '/docs/en/engines/table_engines/mergetree_family/collapsingmergetree',to: '/docs/en/engines/table-engines/mergetree-family/collapsingmergetree'}, 
          {from: '/docs/en/operations/table_engines/collapsingmergetree',to: '/docs/en/engines/table-engines/mergetree-family/collapsingmergetree'}, 
          {from: '/docs/en/engines/table_engines/mergetree_family/custom_partitioning_key',to: '/docs/en/engines/table-engines/mergetree-family/custom-partitioning-key'}, 
          {from: '/docs/en/operations/table_engines/custom_partitioning_key',to: '/docs/en/engines/table-engines/mergetree-family/custom-partitioning-key'}, 
          {from: '/docs/en/engines/table_engines/mergetree_family/graphitemergetree',to: '/docs/en/engines/table-engines/mergetree-family/graphitemergetree'}, 
          {from: '/docs/en/operations/table_engines/graphitemergetree',to: '/docs/en/engines/table-engines/mergetree-family/graphitemergetree'}, 
          {from: '/docs/en/engines/table_engines/mergetree_family/mergetree',to: '/docs/en/engines/table-engines/mergetree-family/mergetree'}, 
          {from: '/docs/en/operations/table_engines/mergetree',to: '/docs/en/engines/table-engines/mergetree-family/mergetree'}, 
          {from: '/docs/en/engines/table_engines/mergetree_family/replacingmergetree',to: '/docs/en/engines/table-engines/mergetree-family/replacingmergetree'}, 
          {from: '/docs/en/operations/table_engines/replacingmergetree',to: '/docs/en/engines/table-engines/mergetree-family/replacingmergetree'}, 
          {from: '/docs/en/engines/table_engines/mergetree_family/replication',to: '/docs/en/engines/table-engines/mergetree-family/replication'}, 
          {from: '/docs/en/operations/table_engines/replication',to: '/docs/en/engines/table-engines/mergetree-family/replication'}, 
          {from: '/docs/en/engines/table_engines/mergetree_family/summingmergetree',to: '/docs/en/engines/table-engines/mergetree-family/summingmergetree'}, 
          {from: '/docs/en/operations/table_engines/summingmergetree',to: '/docs/en/engines/table-engines/mergetree-family/summingmergetree'}, 
          {from: '/docs/en/engines/table_engines/mergetree_family/versionedcollapsingmergetree',to: '/docs/en/engines/table-engines/mergetree-family/versionedcollapsingmergetree'}, 
          {from: '/docs/en/operations/table_engines/versionedcollapsingmergetree',to: '/docs/en/engines/table-engines/mergetree-family/versionedcollapsingmergetree'}, 
          {from: '/docs/en/engines/table_engines/special/',to: '/docs/en/engines/table-engines/special/'}, 
          {from: '/docs/en/engines/table_engines/special/buffer',to: '/docs/en/engines/table-engines/special/buffer'}, 
          {from: '/docs/en/operations/table_engines/buffer',to: '/docs/en/engines/table-engines/special/buffer'}, 
          {from: '/docs/en/engines/table_engines/special/dictionary',to: '/docs/en/engines/table-engines/special/dictionary'}, 
          {from: '/docs/en/operations/table_engines/dictionary',to: '/docs/en/engines/table-engines/special/dictionary'}, 
          {from: '/docs/en/engines/table_engines/special/distributed',to: '/docs/en/engines/table-engines/special/distributed'}, 
          {from: '/docs/en/operations/table_engines/distributed',to: '/docs/en/engines/table-engines/special/distributed'}, 
          {from: '/docs/en/engines/table_engines/special/external_data',to: '/docs/en/engines/table-engines/special/external-data'}, 
          {from: '/docs/en/operations/table_engines/external_data',to: '/docs/en/engines/table-engines/special/external-data'}, 
          {from: '/docs/en/engines/table_engines/special/file',to: '/docs/en/engines/table-engines/special/file'}, 
          {from: '/docs/en/operations/table_engines/file',to: '/docs/en/engines/table-engines/special/file'}, 
          {from: '/docs/en/engines/table_engines/special/generate',to: '/docs/en/engines/table-engines/special/generate'}, 
          {from: '/docs/en/operations/table_engines/generate',to: '/docs/en/engines/table-engines/special/generate'}, 
          {from: '/docs/en/engines/table_engines/special/join',to: '/docs/en/engines/table-engines/special/join'}, 
          {from: '/docs/en/operations/table_engines/join',to: '/docs/en/engines/table-engines/special/join'}, 
          {from: '/docs/en/engines/table_engines/special/materializedview',to: '/docs/en/engines/table-engines/special/materializedview'}, 
          {from: '/docs/en/operations/table_engines/materializedview',to: '/docs/en/engines/table-engines/special/materializedview'}, 
          {from: '/docs/en/engines/table_engines/special/memory',to: '/docs/en/engines/table-engines/special/memory'}, 
          {from: '/docs/en/operations/table_engines/memory',to: '/docs/en/engines/table-engines/special/memory'}, 
          {from: '/docs/en/engines/table_engines/special/merge',to: '/docs/en/engines/table-engines/special/merge'}, 
          {from: '/docs/en/operations/table_engines/merge',to: '/docs/en/engines/table-engines/special/merge'}, 
          {from: '/docs/en/engines/table_engines/special/null',to: '/docs/en/engines/table-engines/special/null'}, 
          {from: '/docs/en/operations/table_engines/null',to: '/docs/en/engines/table-engines/special/null'}, 
          {from: '/docs/en/engines/table_engines/special/set',to: '/docs/en/engines/table-engines/special/set'}, 
          {from: '/docs/en/operations/table_engines/set',to: '/docs/en/engines/table-engines/special/set'}, 
          {from: '/docs/en/engines/table_engines/special/url',to: '/docs/en/engines/table-engines/special/url'}, 
          {from: '/docs/en/operations/table_engines/url',to: '/docs/en/engines/table-engines/special/url'}, 
          {from: '/docs/en/engines/table_engines/special/view',to: '/docs/en/engines/table-engines/special/view'}, 
          {from: '/docs/en/operations/table_engines/view',to: '/docs/en/engines/table-engines/special/view'}, 
          {from: '/docs/en/introduction/possible_silly_questions',to: '/docs/faq/general/'}, 
          {from: '/docs/en/getting_started/',to: '/docs/quick-start'}, 
          {from: '/docs/en/getting_started/example_datasets/',to: '/docs/en/example-datasets'}, 
          {from: '/docs/en/getting_started/example_datasets/amplab_benchmark',to: '/docs/en/example-datasets/amplab-benchmark'}, 
          {from: '/docs/en/getting_started/example_datasets/criteo',to: '/docs/en/example-datasets/criteo'}, 
          {from: '/docs/en/getting_started/example_datasets/metrica',to: '/docs/en/example-datasets/metrica'}, 
          {from: '/docs/en/getting_started/example_datasets/nyc_taxi',to: '/docs/en/example-datasets/nyc-taxi'}, 
          {from: '/docs/en/getting_started/example_datasets/ontime',to: '/docs/en/example-datasets/ontime'}, 
          {from: '/docs/en/getting_started/example_datasets/star_schema',to: '/docs/en/example-datasets/star-schema'}, 
          {from: '/docs/en/getting_started/example_datasets/wikistat',to: '/docs/en/example-datasets/wikistat'}, 
          {from: '/docs/en/getting_started/install',to: '/docs/en/getting-started/install'}, 
          {from: '/docs/en/getting_started/playground',to: '/docs/en/getting-started/playground'}, 
          {from: '/docs/en/getting_started/tutorial',to: '/docs/tutorial'}, 
          {from: '/docs/en/guides/apply_catboost_model',to: '/docs/guides/developer/apply-catboost-model'}, 
          {from: '/docs/en/commercial/cloud',to: '/docs/about-us/cloud'}, 
          {from: '/docs/en/formats',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/capnproto',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/csv',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/csvwithnames',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/json',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/jsoncompact',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/jsoneachrow',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/native',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/null',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/pretty',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/prettycompact',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/prettycompactmonoblock',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/prettynoescapes',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/prettyspace',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/rowbinary',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/tabseparated',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/tabseparatedraw',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/tabseparatedwithnames',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/tabseparatedwithnamesandtypes',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/tskv',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/values',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/vertical',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/verticalraw',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/formats/xml',to: '/docs/en/interfaces/formats'}, 
          {from: '/docs/en/interfaces/http_interface',to: '/docs/en/interfaces/http'}, 
          {from: '/docs/en/interfaces/third_party/',to: '/docs/en/interfaces/third-party/'}, 
          {from: '/docs/en/interfaces/third-party/client_libraries',to: '/docs/en/interfaces/third-party/client-libraries'}, 
          {from: '/docs/en/interfaces/third-party_client_libraries',to: '/docs/en/interfaces/third-party/client-libraries'}, 
          {from: '/docs/en/interfaces/third-party_gui',to: '/docs/en/interfaces/third-party/gui'}, 
          {from: '/docs/en/introduction/distinctive_features',to: '/docs/about-us/distinctive-features'}, 
          {from: '/docs/en/introduction/features_considered_disadvantages',to: '/docs/about-us/distinctive-features'}, 
          {from: '/docs/en/introduction/ya_metrika_task',to: '/docs/about-us/history'}, 
          {from: '/docs/en/operations/access_rights',to: '/docs/en/operations/access-rights'}, 
          {from: '/docs/en/operations/configuration_files',to: '/docs/en/operations/configuration-files'}, 
          {from: '/docs/en/operations/optimizing_performance/',to: '/docs/en/operations/optimizing-performance/'}, 
          {from: '/docs/en/operations/optimizing_performance/sampling_query_profiler',to: '/docs/en/operations/optimizing-performance/sampling-query-profiler'}, 
          {from: '/docs/en/operations/performance/sampling_query_profiler',to: '/docs/en/operations/optimizing-performance/sampling-query-profiler'}, 
          {from: '/docs/en/operations/performance_test',to: '/docs/en/operations/performance-test'}, 
          {from: '/docs/en/operations/server_configuration_parameters/',to: '/docs/en/operations/server-configuration-parameters/'}, 
          {from: '/docs/en/operations/server_settings/',to: '/docs/en/operations/server-configuration-parameters/'}, 
          {from: '/docs/en/operations/server_configuration_parameters/settings',to: '/docs/en/operations/server-configuration-parameters/settings'}, 
          {from: '/docs/en/operations/server_settings/settings',to: '/docs/en/operations/server-configuration-parameters/settings'}, 
          {from: '/docs/en/operations/settings/constraints_on_settings',to: '/docs/en/operations/settings/constraints-on-settings'}, 
          {from: '/docs/en/operations/settings/permissions_for_queries',to: '/docs/en/operations/settings/permissions-for-queries'}, 
          {from: '/docs/en/operations/settings/query_complexity',to: '/docs/en/operations/settings/query-complexity'}, 
          {from: '/docs/en/operations/settings/settings_profiles',to: '/docs/en/operations/settings/settings-profiles'}, 
          {from: '/docs/en/operations/settings/settings_users',to: '/docs/en/operations/settings/settings-users'}, 
          {from: '/docs/en/operations/system_tables',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables/system.asynchronous_metrics',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables/system.clusters',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables/system.columns',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables/system.databases',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables/system.dictionaries',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables/system.events',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables/system.functions',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables/system.merges',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables/system.metrics',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables/system.numbers',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables/system.numbers_mt',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables/system.one',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables/system.parts',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables/system.processes',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables/system.replicas',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables/system.settings',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables/system.tables',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/system_tables/system.zookeeper',to: '/docs/en/operations/system-tables/'}, 
          {from: '/docs/en/operations/utils/',to: '/docs/en/operations/utilities/'}, 
          {from: '/docs/en/operations/utils/clickhouse-benchmark',to: '/docs/en/operations/utilities/clickhouse-benchmark'}, 
          {from: '/docs/en/operations/utils/clickhouse-copier',to: '/docs/en/operations/utilities/clickhouse-copier'}, 
          {from: '/docs/en/operations/utils/clickhouse-local',to: '/docs/en/operations/utilities/clickhouse-local'}, 
          {from: '/docs/en/utils',to: '/docs/en/operations/utilities/'}, 
          {from: '/docs/en/utils/clickhouse-copier',to: '/docs/en/operations/utilities/clickhouse-copier'}, 
          {from: '/docs/en/utils/clickhouse-local',to: '/docs/en/operations/utilities/clickhouse-local'}, 
          {from: '/docs/en/query_language/',to: '/docs/en/sql-reference/'}, 
          {from: '/docs/en/sql_reference/',to: '/docs/en/sql-reference/'}, 
          {from: '/docs/en/query_language/agg_functions/',to: '/docs/en/sql-reference/aggregate-functions/'}, 
          {from: '/docs/en/sql_reference/aggregate_functions/',to: '/docs/en/sql-reference/aggregate-functions/'}, 
          {from: '/docs/en/query_language/agg_functions/combinators',to: '/docs/en/sql-reference/aggregate-functions/combinators'}, 
          {from: '/docs/en/sql_reference/aggregate_functions/combinators',to: '/docs/en/sql-reference/aggregate-functions/combinators'}, 
          {from: '/docs/en/query_language/agg_functions/parametric_functions',to: '/docs/en/sql-reference/aggregate-functions/parametric-functions'}, 
          {from: '/docs/en/sql_reference/aggregate_functions/parametric_functions',to: '/docs/en/sql-reference/aggregate-functions/parametric-functions'}, 
          {from: '/docs/en/query_language/agg_functions/reference',to: '/docs/en/sql-reference/aggregate-functions/reference/'}, 
          {from: '/docs/en/sql_reference/aggregate_functions/reference',to: '/docs/en/sql-reference/aggregate-functions/reference/'}, 
          {from: '/docs/en/sql_reference/ansi',to: '/docs/en/sql-reference/ansi'}, 
          {from: '/docs/en/data_types/',to: '/docs/en/sql-reference/data-types/'}, 
          {from: '/docs/en/sql_reference/data_types/',to: '/docs/en/sql-reference/data-types/'}, 
          {from: '/docs/en/data_types/nested_data_structures/aggregatefunction',to: '/docs/en/sql-reference/data-types/aggregatefunction'}, 
          {from: '/docs/en/sql_reference/data_types/aggregatefunction',to: '/docs/en/sql-reference/data-types/aggregatefunction'}, 
          {from: '/docs/en/data_types/array',to: '/docs/en/sql-reference/data-types/array'}, 
          {from: '/docs/en/sql_reference/data_types/array',to: '/docs/en/sql-reference/data-types/array'}, 
          {from: '/docs/en/data_types/boolean',to: '/docs/en/sql-reference/data-types/boolean'}, 
          {from: '/docs/en/sql_reference/data_types/boolean',to: '/docs/en/sql-reference/data-types/boolean'}, 
          {from: '/docs/en/data_types/date',to: '/docs/en/sql-reference/data-types/date'}, 
          {from: '/docs/en/sql_reference/data_types/date',to: '/docs/en/sql-reference/data-types/date'}, 
          {from: '/docs/en/data_types/datetime',to: '/docs/en/sql-reference/data-types/datetime'}, 
          {from: '/docs/en/sql_reference/data_types/datetime',to: '/docs/en/sql-reference/data-types/datetime'}, 
          {from: '/docs/en/data_types/datetime64',to: '/docs/en/sql-reference/data-types/datetime64'}, 
          {from: '/docs/en/sql_reference/data_types/datetime64',to: '/docs/en/sql-reference/data-types/datetime64'}, 
          {from: '/docs/en/data_types/decimal',to: '/docs/en/sql-reference/data-types/decimal'}, 
          {from: '/docs/en/sql_reference/data_types/decimal',to: '/docs/en/sql-reference/data-types/decimal'}, 
          {from: '/docs/en/sql-reference/data-types/domains/overview',to: '/docs/en/sql-reference/data-types/domains/'}, 
          {from: '/docs/en/sql_reference/data_types/domains/',to: '/docs/en/sql-reference/data-types/domains/'}, 
          {from: '/docs/en/data_types/domains/ipv4',to: '/docs/en/sql-reference/data-types/domains/ipv4'}, 
          {from: '/docs/en/sql_reference/data_types/domains/ipv4',to: '/docs/en/sql-reference/data-types/domains/ipv4'}, 
          {from: '/docs/en/data_types/domains/ipv6',to: '/docs/en/sql-reference/data-types/domains/ipv6'}, 
          {from: '/docs/en/sql_reference/data_types/domains/ipv6',to: '/docs/en/sql-reference/data-types/domains/ipv6'}, 
          {from: '/docs/en/data_types/domains/overview',to: '/docs/en/sql-reference/data-types/domains/'}, 
          {from: '/docs/en/sql_reference/data_types/domains/overview',to: '/docs/en/sql-reference/data-types/domains/'}, 
          {from: '/docs/en/data_types/enum',to: '/docs/en/sql-reference/data-types/enum'}, 
          {from: '/docs/en/sql_reference/data_types/enum',to: '/docs/en/sql-reference/data-types/enum'}, 
          {from: '/docs/en/data_types/fixedstring',to: '/docs/en/sql-reference/data-types/fixedstring'}, 
          {from: '/docs/en/sql_reference/data_types/fixedstring',to: '/docs/en/sql-reference/data-types/fixedstring'}, 
          {from: '/docs/en/data_types/float',to: '/docs/en/sql-reference/data-types/float'}, 
          {from: '/docs/en/sql_reference/data_types/float',to: '/docs/en/sql-reference/data-types/float'}, 
          {from: '/docs/en/data_types/int_uint',to: '/docs/en/sql-reference/data-types/int-uint'}, 
          {from: '/docs/en/sql_reference/data_types/int_uint',to: '/docs/en/sql-reference/data-types/int-uint'}, 
          {from: '/docs/en/data_types/nested_data_structures/',to: '/docs/en/sql-reference/data-types/nested-data-structures/'}, 
          {from: '/docs/en/sql_reference/data_types/nested_data_structures/',to: '/docs/en/sql-reference/data-types/nested-data-structures/'}, 
          {from: '/docs/en/data_types/nested_data_structures/nested',to: '/docs/en/sql-reference/data-types/nested-data-structures/nested'}, 
          {from: '/docs/en/sql_reference/data_types/nested_data_structures/nested',to: '/docs/en/sql-reference/data-types/nested-data-structures/nested'}, 
          {from: '/docs/en/data_types/nullable',to: '/docs/en/sql-reference/data-types/nullable'}, 
          {from: '/docs/en/sql_reference/data_types/nullable',to: '/docs/en/sql-reference/data-types/nullable'}, 
          {from: '/docs/en/sql_reference/data_types/simpleaggregatefunction',to: '/docs/en/sql-reference/data-types/simpleaggregatefunction'}, 
          {from: '/docs/en/data_types/special_data_types/',to: '/docs/en/sql-reference/data-types/special-data-types/'}, 
          {from: '/docs/en/sql_reference/data_types/special_data_types/',to: '/docs/en/sql-reference/data-types/special-data-types/'}, 
          {from: '/docs/en/data_types/special_data_types/expression',to: '/docs/en/sql-reference/data-types/special-data-types/expression'}, 
          {from: '/docs/en/sql_reference/data_types/special_data_types/expression',to: '/docs/en/sql-reference/data-types/special-data-types/expression'}, 
          {from: '/docs/en/data_types/special_data_types/interval',to: '/docs/en/sql-reference/data-types/special-data-types/interval'}, 
          {from: '/docs/en/sql_reference/data_types/special_data_types/interval',to: '/docs/en/sql-reference/data-types/special-data-types/interval'}, 
          {from: '/docs/en/data_types/special_data_types/nothing',to: '/docs/en/sql-reference/data-types/special-data-types/nothing'}, 
          {from: '/docs/en/sql_reference/data_types/special_data_types/nothing',to: '/docs/en/sql-reference/data-types/special-data-types/nothing'}, 
          {from: '/docs/en/data_types/special_data_types/set',to: '/docs/en/sql-reference/data-types/special-data-types/set'}, 
          {from: '/docs/en/sql_reference/data_types/special_data_types/set',to: '/docs/en/sql-reference/data-types/special-data-types/set'}, 
          {from: '/docs/en/data_types/string',to: '/docs/en/sql-reference/data-types/string'}, 
          {from: '/docs/en/sql_reference/data_types/string',to: '/docs/en/sql-reference/data-types/string'}, 
          {from: '/docs/en/data_types/tuple',to: '/docs/en/sql-reference/data-types/tuple'}, 
          {from: '/docs/en/sql_reference/data_types/tuple',to: '/docs/en/sql-reference/data-types/tuple'}, 
          {from: '/docs/en/data_types/uuid',to: '/docs/en/sql-reference/data-types/uuid'}, 
          {from: '/docs/en/sql_reference/data_types/uuid',to: '/docs/en/sql-reference/data-types/uuid'}, 
          {from: '/docs/en/query_language/dicts/',to: '/docs/en/sql-reference/dictionaries/'}, 
          {from: '/docs/en/sql_reference/dictionaries/',to: '/docs/en/sql-reference/dictionaries/'}, 
          {from: '/docs/en/sql_reference/dictionaries/external_dictionaries/',to: '/docs/en/sql-reference/dictionaries/external-dictionaries'}, 
          {from: '/docs/en/query_language/dicts/external_dicts',to: '/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts'}, 
          {from: '/docs/en/sql_reference/dictionaries/external_dictionaries/external_dicts',to: '/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts'}, 
          {from: '/docs/en/query_language/dicts/external_dicts_dict',to: '/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict'}, 
          {from: '/docs/en/sql_reference/dictionaries/external_dictionaries/external_dicts_dict',to: '/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict'}, 
          {from: '/docs/en/query_language/dicts/external_dicts_dict_hierarchical',to: '/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-hierarchical'}, 
          {from: '/docs/en/sql_reference/dictionaries/external_dictionaries/external_dicts_dict_hierarchical',to: '/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-hierarchical'}, 
          {from: '/docs/en/query_language/dicts/external_dicts_dict_layout',to: '/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-layout'}, 
          {from: '/docs/en/sql_reference/dictionaries/external_dictionaries/external_dicts_dict_layout',to: '/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-layout'}, 
          {from: '/docs/en/query_language/dicts/external_dicts_dict_lifetime',to: '/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-lifetime'}, 
          {from: '/docs/en/sql_reference/dictionaries/external_dictionaries/external_dicts_dict_lifetime',to: '/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-lifetime'}, 
          {from: '/docs/en/query_language/dicts/external_dicts_dict_sources',to: '/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-sources'}, 
          {from: '/docs/en/sql_reference/dictionaries/external_dictionaries/external_dicts_dict_sources',to: '/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-sources'}, 
          {from: '/docs/en/query_language/dicts/external_dicts_dict_structure',to: '/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-structure'}, 
          {from: '/docs/en/sql_reference/dictionaries/external_dictionaries/external_dicts_dict_structure',to: '/docs/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-structure'}, 
          {from: '/docs/en/query_language/dicts/internal_dicts',to: '/docs/en/sql-reference/dictionaries/internal-dicts'}, 
          {from: '/docs/en/sql_reference/dictionaries/internal_dicts',to: '/docs/en/sql-reference/dictionaries/internal-dicts'}, 
          {from: '/docs/en/query_language/functions/',to: '/docs/en/sql-reference/functions/'}, 
          {from: '/docs/en/sql_reference/functions/',to: '/docs/en/sql-reference/functions/'}, 
          {from: '/docs/en/query_language/functions/arithmetic_functions',to: '/docs/en/sql-reference/functions/arithmetic-functions'}, 
          {from: '/docs/en/sql_reference/functions/arithmetic_functions',to: '/docs/en/sql-reference/functions/arithmetic-functions'}, 
          {from: '/docs/en/query_language/functions/array_functions',to: '/docs/en/sql-reference/functions/array-functions'}, 
          {from: '/docs/en/sql_reference/functions/array_functions',to: '/docs/en/sql-reference/functions/array-functions'}, 
          {from: '/docs/en/query_language/functions/array_join',to: '/docs/en/sql-reference/functions/array-join'}, 
          {from: '/docs/en/sql_reference/functions/array_join',to: '/docs/en/sql-reference/functions/array-join'}, 
          {from: '/docs/en/query_language/functions/bit_functions',to: '/docs/en/sql-reference/functions/bit-functions'}, 
          {from: '/docs/en/sql_reference/functions/bit_functions',to: '/docs/en/sql-reference/functions/bit-functions'}, 
          {from: '/docs/en/query_language/functions/bitmap_functions',to: '/docs/en/sql-reference/functions/bitmap-functions'}, 
          {from: '/docs/en/sql_reference/functions/bitmap_functions',to: '/docs/en/sql-reference/functions/bitmap-functions'}, 
          {from: '/docs/en/query_language/functions/comparison_functions',to: '/docs/en/sql-reference/functions/comparison-functions'}, 
          {from: '/docs/en/sql_reference/functions/comparison_functions',to: '/docs/en/sql-reference/functions/comparison-functions'}, 
          {from: '/docs/en/query_language/functions/conditional_functions',to: '/docs/en/sql-reference/functions/conditional-functions'}, 
          {from: '/docs/en/sql_reference/functions/conditional_functions',to: '/docs/en/sql-reference/functions/conditional-functions'}, 
          {from: '/docs/en/query_language/functions/date_time_functions',to: '/docs/en/sql-reference/functions/date-time-functions'}, 
          {from: '/docs/en/sql_reference/functions/date_time_functions',to: '/docs/en/sql-reference/functions/date-time-functions'}, 
          {from: '/docs/en/query_language/functions/encoding_functions',to: '/docs/en/sql-reference/functions/encoding-functions'}, 
          {from: '/docs/en/sql_reference/functions/encoding_functions',to: '/docs/en/sql-reference/functions/encoding-functions'}, 
          {from: '/docs/en/query_language/functions/ext_dict_functions',to: '/docs/en/sql-reference/functions/ext-dict-functions'}, 
          {from: '/docs/en/sql_reference/functions/ext_dict_functions',to: '/docs/en/sql-reference/functions/ext-dict-functions'}, 
          {from: '/docs/en/query_language/functions/functions_for_nulls',to: '/docs/en/sql-reference/functions/functions-for-nulls'}, 
          {from: '/docs/en/sql_reference/functions/functions_for_nulls',to: '/docs/en/sql-reference/functions/functions-for-nulls'}, 
          {from: '/docs/en/query_language/functions/geo',to: '/docs/en/sql-reference/functions/geo/'}, 
          {from: '/docs/en/sql_reference/functions/geo',to: '/docs/en/sql-reference/functions/geo/'}, 
          {from: '/docs/en/query_language/functions/hash_functions',to: '/docs/en/sql-reference/functions/hash-functions'}, 
          {from: '/docs/en/sql_reference/functions/hash_functions',to: '/docs/en/sql-reference/functions/hash-functions'}, 
          {from: '/docs/en/query_language/functions/in_functions',to: '/docs/en/sql-reference/functions/in-functions'}, 
          {from: '/docs/en/sql_reference/functions/in_functions',to: '/docs/en/sql-reference/functions/in-functions'}, 
          {from: '/docs/en/query_language/functions/introspection',to: '/docs/en/sql-reference/functions/introspection'}, 
          {from: '/docs/en/sql_reference/functions/introspection',to: '/docs/en/sql-reference/functions/introspection'}, 
          {from: '/docs/en/query_language/functions/ip_address_functions',to: '/docs/en/sql-reference/functions/ip-address-functions'}, 
          {from: '/docs/en/sql_reference/functions/ip_address_functions',to: '/docs/en/sql-reference/functions/ip-address-functions'}, 
          {from: '/docs/en/query_language/functions/json_functions',to: '/docs/en/sql-reference/functions/json-functions'}, 
          {from: '/docs/en/sql_reference/functions/json_functions',to: '/docs/en/sql-reference/functions/json-functions'}, 
          {from: '/docs/en/query_language/functions/logical_functions',to: '/docs/en/sql-reference/functions/logical-functions'}, 
          {from: '/docs/en/sql_reference/functions/logical_functions',to: '/docs/en/sql-reference/functions/logical-functions'}, 
          {from: '/docs/en/query_language/functions/machine_learning_functions',to: '/docs/en/sql-reference/functions/machine-learning-functions'}, 
          {from: '/docs/en/sql_reference/functions/machine_learning_functions',to: '/docs/en/sql-reference/functions/machine-learning-functions'}, 
          {from: '/docs/en/query_language/functions/math_functions',to: '/docs/en/sql-reference/functions/math-functions'}, 
          {from: '/docs/en/sql_reference/functions/math_functions',to: '/docs/en/sql-reference/functions/math-functions'}, 
          {from: '/docs/en/query_language/functions/other_functions',to: '/docs/en/sql-reference/functions/other-functions'}, 
          {from: '/docs/en/sql_reference/functions/other_functions',to: '/docs/en/sql-reference/functions/other-functions'}, 
          {from: '/docs/en/query_language/functions/random_functions',to: '/docs/en/sql-reference/functions/random-functions'}, 
          {from: '/docs/en/sql_reference/functions/random_functions',to: '/docs/en/sql-reference/functions/random-functions'}, 
          {from: '/docs/en/query_language/functions/rounding_functions',to: '/docs/en/sql-reference/functions/rounding-functions'}, 
          {from: '/docs/en/sql_reference/functions/rounding_functions',to: '/docs/en/sql-reference/functions/rounding-functions'}, 
          {from: '/docs/en/query_language/functions/splitting_merging_functions',to: '/docs/en/sql-reference/functions/splitting-merging-functions'}, 
          {from: '/docs/en/sql_reference/functions/splitting_merging_functions',to: '/docs/en/sql-reference/functions/splitting-merging-functions'}, 
          {from: '/docs/en/query_language/functions/string_functions',to: '/docs/en/sql-reference/functions/string-functions'}, 
          {from: '/docs/en/sql_reference/functions/string_functions',to: '/docs/en/sql-reference/functions/string-functions'}, 
          {from: '/docs/en/query_language/functions/string_replace_functions',to: '/docs/en/sql-reference/functions/string-replace-functions'}, 
          {from: '/docs/en/sql_reference/functions/string_replace_functions',to: '/docs/en/sql-reference/functions/string-replace-functions'}, 
          {from: '/docs/en/query_language/functions/string_search_functions',to: '/docs/en/sql-reference/functions/string-search-functions'}, 
          {from: '/docs/en/sql_reference/functions/string_search_functions',to: '/docs/en/sql-reference/functions/string-search-functions'}, 
          {from: '/docs/en/query_language/functions/type_conversion_functions',to: '/docs/en/sql-reference/functions/type-conversion-functions'}, 
          {from: '/docs/en/sql_reference/functions/type_conversion_functions',to: '/docs/en/sql-reference/functions/type-conversion-functions'}, 
          {from: '/docs/en/query_language/functions/url_functions',to: '/docs/en/sql-reference/functions/url-functions'}, 
          {from: '/docs/en/sql_reference/functions/url_functions',to: '/docs/en/sql-reference/functions/url-functions'}, 
          {from: '/docs/en/query_language/functions/uuid_functions',to: '/docs/en/sql-reference/functions/uuid-functions'}, 
          {from: '/docs/en/sql_reference/functions/uuid_functions',to: '/docs/en/sql-reference/functions/uuid-functions'}, 
          {from: '/docs/en/query_language/functions/ym_dict_functions',to: '/docs/en/sql-reference/functions/ym-dict-functions'}, 
          {from: '/docs/en/sql_reference/functions/ym_dict_functions',to: '/docs/en/sql-reference/functions/ym-dict-functions'}, 
          {from: '/docs/en/query_language/operators',to: '/docs/en/sql-reference/operators/'}, 
          {from: '/docs/en/sql_reference/operators',to: '/docs/en/sql-reference/operators/'}, 
          {from: '/docs/en/sql_reference/statements/',to: '/docs/en/sql-reference/statements/'}, 
          {from: '/docs/en/query_language/alter',to: '/docs/en/sql-reference/statements/alter/'}, 
          {from: '/docs/en/sql_reference/statements/alter',to: '/docs/en/sql-reference/statements/alter/'}, 
          {from: '/docs/en/query_language/create',to: '/docs/en/sql-reference/statements/create/'}, 
          {from: '/docs/en/sql_reference/statements/create',to: '/docs/en/sql-reference/statements/create/'}, 
          {from: '/docs/en/query_language/insert_into',to: '/docs/en/sql-reference/statements/insert-into'}, 
          {from: '/docs/en/sql_reference/statements/insert_into',to: '/docs/en/sql-reference/statements/insert-into'}, 
          {from: '/docs/en/query_language/misc',to: '/docs/en/sql-reference/statements/misc'}, 
          {from: '/docs/en/sql_reference/statements/misc',to: '/docs/en/sql-reference/statements/misc'}, 
          {from: '/docs/en/query_language/select',to: '/docs/en/sql-reference/statements/select/'}, 
          {from: '/docs/en/sql_reference/statements/select',to: '/docs/en/sql-reference/statements/select/'}, 
          {from: '/docs/en/query_language/show',to: '/docs/en/sql-reference/statements/show'}, 
          {from: '/docs/en/sql_reference/statements/show',to: '/docs/en/sql-reference/statements/show'}, 
          {from: '/docs/en/query_language/system',to: '/docs/en/sql-reference/statements/system'}, 
          {from: '/docs/en/sql_reference/statements/system',to: '/docs/en/sql-reference/statements/system'}, 
          {from: '/docs/en/query_language/syntax',to: '/docs/en/sql-reference/syntax'}, 
          {from: '/docs/en/sql_reference/syntax',to: '/docs/en/sql-reference/syntax'}, 
          {from: '/docs/en/query_language/table_functions/',to: '/docs/en/sql-reference/table-functions/'}, 
          {from: '/docs/en/sql_reference/table_functions/',to: '/docs/en/sql-reference/table-functions/'}, 
          {from: '/docs/en/query_language/table_functions/file',to: '/docs/en/sql-reference/table-functions/file'}, 
          {from: '/docs/en/sql_reference/table_functions/file',to: '/docs/en/sql-reference/table-functions/file'}, 
          {from: '/docs/en/query_language/table_functions/generate',to: '/docs/en/sql-reference/table-functions/generate'}, 
          {from: '/docs/en/sql_reference/table_functions/generate',to: '/docs/en/sql-reference/table-functions/generate'}, 
          {from: '/docs/en/query_language/table_functions/hdfs',to: '/docs/en/sql-reference/table-functions/hdfs'}, 
          {from: '/docs/en/sql_reference/table_functions/hdfs',to: '/docs/en/sql-reference/table-functions/hdfs'}, 
          {from: '/docs/en/query_language/table_functions/input',to: '/docs/en/sql-reference/table-functions/input'}, 
          {from: '/docs/en/sql_reference/table_functions/input',to: '/docs/en/sql-reference/table-functions/input'}, 
          {from: '/docs/en/query_language/table_functions/jdbc',to: '/docs/en/sql-reference/table-functions/jdbc'}, 
          {from: '/docs/en/sql_reference/table_functions/jdbc',to: '/docs/en/sql-reference/table-functions/jdbc'}, 
          {from: '/docs/en/query_language/table_functions/merge',to: '/docs/en/sql-reference/table-functions/merge'}, 
          {from: '/docs/en/sql_reference/table_functions/merge',to: '/docs/en/sql-reference/table-functions/merge'}, 
          {from: '/docs/en/query_language/table_functions/mysql',to: '/docs/en/sql-reference/table-functions/mysql'}, 
          {from: '/docs/en/sql_reference/table_functions/mysql',to: '/docs/en/sql-reference/table-functions/mysql'}, 
          {from: '/docs/en/query_language/table_functions/numbers',to: '/docs/en/sql-reference/table-functions/numbers'}, 
          {from: '/docs/en/sql_reference/table_functions/numbers',to: '/docs/en/sql-reference/table-functions/numbers'}, 
          {from: '/docs/en/query_language/table_functions/odbc',to: '/docs/en/sql-reference/table-functions/odbc'}, 
          {from: '/docs/en/sql_reference/table_functions/odbc',to: '/docs/en/sql-reference/table-functions/odbc'}, 
          {from: '/docs/en/query_language/table_functions/remote',to: '/docs/en/sql-reference/table-functions/remote'}, 
          {from: '/docs/en/sql_reference/table_functions/remote',to: '/docs/en/sql-reference/table-functions/remote'}, 
          {from: '/docs/en/query_language/table_functions/url',to: '/docs/en/sql-reference/table-functions/url'}, 
          {from: '/docs/en/sql_reference/table_functions/url',to: '/docs/en/sql-reference/table-functions/url'}, 
          {from: '/docs/en/whats_new/',to: '/docs/en/whats-new/'}, 
          {from: '/docs/en/changelog/',to: '/docs/en/whats-new/changelog/'}, 
          {from: '/docs/en/whats_new/changelog/',to: '/docs/en/whats-new/changelog/'}, 
          {from: '/docs/en/changelog/2017',to: '/docs/en/whats-new/changelog/2017'}, 
          {from: '/docs/en/whats_new/changelog/2017',to: '/docs/en/whats-new/changelog/2017'}, 
          {from: '/docs/en/changelog/2018',to: '/docs/en/whats-new/changelog/2018'}, 
          {from: '/docs/en/whats_new/changelog/2018',to: '/docs/en/whats-new/changelog/2018'}, 
          {from: '/docs/en/changelog/2019',to: '/docs/en/whats-new/changelog/2019'}, 
          {from: '/docs/en/whats_new/changelog/2019',to: '/docs/en/whats-new/changelog/2019'}, 
          {from: '/docs/en/extended_roadmap',to: '/docs/en/whats-new/roadmap'}, 
          {from: '/docs/en/roadmap',to: '/docs/en/whats-new/roadmap'}, 
          {from: '/docs/en/whats_new/roadmap',to: '/docs/en/whats-new/roadmap'}, 
          {from: '/docs/en/security_changelog',to: '/docs/en/whats-new/security-changelog'}, 
          {from: '/docs/en/whats_new/security_changelog',to: '/docs/en/whats-new/security-changelog'}, 
          {from: '/docs/en/introduction/',to: '/docs/intro'},           
        ],
        createRedirects(existingPath) {
          var response = [];

          if (existingPath.includes('/en/')) {
            return [
              existingPath.replaceAll('/en/', '/ja/'),
              existingPath.replaceAll('/en/', '/ru/'),
              existingPath.replaceAll('/en/', '/zh/'),
            ];
          } 
          return undefined; // Return a falsy value: no redirect created
        },
      },
    ]
  ],

  themes: ['@docusaurus/theme-live-codeblock'],

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          editCurrentVersion: true,
          showLastUpdateTime: false,
          sidebarCollapsed: true,
          exclude: [
            'reference/commercial',
            'reference/faq',
            'reference/getting-started',
            'reference/guides',
            'reference/introduction',
            'reference/whats-new',
            'integrations/kafka/code'
          ],
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      disableSwitch: true,
      autoCollapseSidebarCategories: true,
      navbar: {
        title: 'ClickHouse',
        hideOnScroll: true,
        logo: {
          alt: 'ClickHouse',
          src: 'img/clickhouse.svg',
          href: '/docs/'
        },
        items: [
          {
            type: 'doc',
            docId: 'intro',
            position: 'left',
            label: 'Docs',
          },
          {
            type: 'search',
            position: 'right',
          },
        ],
      },
      footer: {
        style: 'light',
        links: [
          {
            title: 'ClickHouse',
            items: [
              {
                label: 'Company',
                to: 'https://clickhouse.com/',
              },
              {
                label: 'ClickHouse as a Service',
                to: 'https://clickhouse.com/cloud/',
              },              
              {
                label: 'Careers',
                to: 'https://clickhouse.com/careers/',
              },
              {
                label: 'Learn ClickHouse',
                to: 'https://clickhouse.com/learn/',
              },
            ],
          },
          {
            title: 'Community',
            items: [
              {
                label: 'GitHub',
                href: 'https://github.com/ClickHouse/ClickHouse',
              },
              {
                label: 'Blog',
                href: 'https://clickhouse.com/blog/en/',
              },
              {
                label: 'YouTube',
                href: 'https://www.youtube.com/c/ClickHouseDB',
              },
              {
                label: 'Twitter',
                href: 'https://twitter.com/ClickHouseDB',
              },
              {
                label: 'Slack',
                href: 'https://join.slack.com/t/clickhousedb/shared_invite/zt-rxm3rdrk-lIUmhLC3V8WTaL0TGxsOmg',
              },
            ],
          },
          {
            title: 'Policies',
            items: [
              {
                label: 'Trademark Policy',
                to: 'https://clickhouse.com/legal/trademark-policy/',
              },
              {
                label: 'Privacy Policy',
                to: 'https://clickhouse.com/legal/privacy-policy/',
              },
              {
                label: 'Cookie Policy',
                to: 'https://clickhouse.com/legal/cookie-policy/',
              },
            ],
          },
        ],
        logo: {
          alt: 'ClickHouse Documentation',
          src: 'img/logo.png'
        },
        copyright: `Copyright © 2016 - ${new Date().getFullYear()} ClickHouse, Inc. ClickHouse Docs provided under the Creative Commons CC BY-NC-SA license. ClickHouse is a registered trademark of ClickHouse, Inc.`,
      },
      prism: {
        theme: clickhouseTheme,
        additionalLanguages: ['java','cpp'],
      },
      colorMode: {
        disableSwitch: true,
      },
/*      announcementBar: {
        id: 'support_us',
        content:
          'Check out our new 25-minute video on <a href="https://clickhouse.com/company/events/getting-started-with-clickhouse/" target="_blank"> Getting Started with ClickHouse</a>',
        backgroundColor: '#0057b7',
        textColor: '#ffffff',
        isCloseable: false,
      }, 
*/
    }),
};

module.exports = config;
