const lightTheme = require('prism-react-renderer/themes/vsLight');
const darkTheme = require('prism-react-renderer/themes/vsDark');

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'ClickHouse Docs',
  tagline: 'Documentation, quick starts, user guides, technical references, FAQs and more...',
  url: 'https://clickhouse.com',
  baseUrl: '/docs/',
  onBrokenLinks: 'error',
  onBrokenMarkdownLinks: 'error',
  favicon: 'img/favicon.ico',
  organizationName: 'ClickHouse',
  projectName: 'clickhouse-docs',

  themes: ['@docusaurus/theme-live-codeblock'],
  scripts: [
    'https://docs-content.clickhouse.tech/docs/js/analytics.js',
  ],
  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          editCurrentVersion: true,
          editUrl: ({ docPath }) => {
            if (docPath.includes('en/development') ||
              docPath.includes('en/engines') ||
              docPath.includes('en/getting-started') ||
              docPath.includes('en/interfaces') ||
              docPath.includes('en/operations') ||
              docPath.includes('en/sql-reference') ||
              docPath.startsWith('ru') ||
              docPath.startsWith('zh')
            ) {
              return 'https://github.com/ClickHouse/ClickHouse/tree/master/docs/' + docPath;

            } else {
              return 'https://github.com/ClickHouse/clickhouse-docs/blob/main/docs/' + docPath;
            }
          },
          showLastUpdateTime: false,
          sidebarCollapsed: true,
          routeBasePath: '/',
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
        gtag: {
          trackingID: 'G-KF1LLRTQ5Q',
        }
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      algolia: {
        appId: '62VCH2MD74',
        apiKey: '65b43d2f45ca1a0ca682116b455f7839',
        indexName: 'clickhouse',
        contextualSearch: false,
        searchPagePath: 'search',
      },
      image: 'img/logo.png',
      docs: {
        sidebar: {
          autoCollapseCategories: true,
        }
      },
      //      autoCollapseSidebarCategories: true,
      navbar: {
        hideOnScroll: false,
        title: 'ClickHouse',
        logo: {
          alt: 'ClickHouse',
          src: 'img/logo_without_text.svg',
          href: 'https://clickhouse.com/',
        },
        items: [
          {
            type: 'dropdown',
            label: 'Product',
            className: 'ch-menu',
            position: 'left',
            items: [
              {
                label: 'ClickHouse Cloud',
                to: 'https://clickhouse.com/cloud'
              },
              {
                label: 'ClickHouse Open Source',
                to: 'https://clickhouse.com/clickhouse'
              },
            ]
          },
          {
            position: 'left',
            label: 'Use Cases',
            className: 'ch-menu',
            to: 'https://clickhouse.com/customer-stories'
          },
          {
            type: 'dropdown',
            label: 'Company',
            className: 'ch-menu',
            position: 'left',
            items: [
              {
                label: 'Blog',
                to: 'https://clickhouse.com/blog',
              },
              {
                label: 'Our story',
                to: 'https://clickhouse.com/company/our-story'
              },
              {
                label: 'Careers',
                to: 'https://clickhouse.com/company/careers'
              },
              {
                label: 'Contact us',
                to: 'https://clickhouse.com/company/contact'
              },
              {
                label: 'News and events',
                to: 'https://clickhouse.com/company/news-events'
              },
            ]
          },
          {
            type: 'doc',
            docId: 'en/home',
            position: 'left',
            className: 'ch-menu',
            label: 'Docs',
          },
          {
            position: 'left',
            label: 'Pricing',
            className: 'ch-menu',
            to: 'https://clickhouse.com/pricing',
          },
          {
            href: 'https://clickhouse.cloud/signUp',
            position: 'right',
            className: 'header-signup-button',
            label: 'Try for Free',
          },
          {
            type: 'dropdown',
            label: 'Language',
            position: 'right',
            items: [
              {
                label: 'English',
                to: '/en/home'
              },
              {
                label: 'Russian',
                to: '/ru',
              },
              {
                label: 'Chinese',
                to: '/zh',
              }
            ]
          },
          {
            type: 'search',
            position: 'right',
          },
        ],
      },
      footer: {
        style: 'light',
        links: [
          {
            title: 'ClickHouse',
            items: [
              {
                label: 'Company',
                to: 'https://clickhouse.com/',
              },
              {
                label: 'ClickHouse as a Service',
                to: 'https://clickhouse.com/cloud/',
              },
              {
                label: 'Careers',
                to: 'https://clickhouse.com/careers/',
              },
              {
                label: 'Learn ClickHouse',
                to: 'https://clickhouse.com/learn/',
              },
            ],
          },
          {
            title: 'Community',
            items: [
              {
                label: 'GitHub',
                href: 'https://github.com/ClickHouse/ClickHouse',
              },
              {
                label: 'Blog',
                href: 'https://clickhouse.com/blog/',
              },
              {
                label: 'Meetup',
                href: 'https://www.meetup.com/pro/clickhouse/',
              },
              {
                label: 'YouTube',
                href: 'https://www.youtube.com/c/ClickHouseDB',
              },
              {
                label: 'Twitter',
                href: 'https://twitter.com/ClickHouseDB',
              },
              {
                label: 'Slack',
                href: 'https://join.slack.com/t/clickhousedb/shared_invite/zt-rxm3rdrk-lIUmhLC3V8WTaL0TGxsOmg',
              },
            ],
          },
          {
            title: 'Policies',
            items: [
              {
                label: 'Trademark Policy',
                to: 'https://clickhouse.com/legal/trademark-policy/',
              },
              {
                label: 'Privacy Policy',
                to: 'https://clickhouse.com/legal/privacy-policy/',
              },
              {
                label: 'Cookie Policy',
                to: 'https://clickhouse.com/legal/cookie-policy/',
              },
            ],
          },
        ],
        logo: {
          alt: 'ClickHouse Documentation',
          src: 'img/logo_without_text.svg',
        },
        copyright: `Copyright &copy; 2016&ndash;${new Date().getFullYear()} ClickHouse, Inc. ClickHouse Docs provided under the Creative Commons CC BY-NC-SA 4.0 license. ClickHouse&reg; is a registered trademark of ClickHouse, Inc.`,
      },
      prism: {
        theme: lightTheme,
        darkTheme: darkTheme,
        additionalLanguages: ['java', 'cpp'],
        magicComments: [
          // Remember to extend the default highlight class name as well!
          {
            className: 'theme-code-block-highlighted-line',
            line: 'highlight-next-line',
            block: { start: 'highlight-start', end: 'highlight-end' },
          },
        ],
      },
      colorMode: {
        disableSwitch: false,
        respectPrefersColorScheme: true,
      },
      /*      announcementBar: {
              id: 'support_us',
              content:
                'Check out our new 25-minute video on <a href="https://clickhouse.com/company/events/getting-started-with-clickhouse/" target="_blank"> Getting Started with ClickHouse</a>',
              backgroundColor: '#0057b7',
              textColor: '#ffffff',
              isCloseable: false,
            },
      */
    }),

  plugins: [
    'remark-docusaurus-tabs',
    [
      '@docusaurus/plugin-client-redirects',
      {
        redirects: [
          { from: '/en/connect-a-ui', to: '/en/integrations/data-visualization' },
          { from: '/en/development/browse_code', to: '/en/development/developer-instruction' },
          { from: '/en/development/browse-code', to: '/en/development/developer-instruction' },
          { from: '/en/development/build_cross_arm', to: '/en/development/build-cross-arm' },
          { from: '/en/development/build_cross_osx', to: '/en/development/build-cross-osx' },
          { from: '/en/development/build_osx', to: '/en/development/build-osx' },
          { from: '/en/development/developer_instruction', to: '/en/development/developer-instruction' },
          { from: '/en/database_engines/', to: '/en/engines/database-engines/' },
          { from: '/en/engines/database_engines/', to: '/en/engines/database-engines/' },
          { from: '/en/database_engines/lazy', to: '/en/engines/database-engines/lazy' },
          { from: '/en/engines/database_engines/lazy', to: '/en/engines/database-engines/lazy' },
          { from: '/en/database_engines/mysql', to: '/en/engines/database-engines/mysql' },
          { from: '/en/engines/database_engines/mysql', to: '/en/engines/database-engines/mysql' },
          { from: '/en/engines/table_engines/', to: '/en/engines/table-engines/' },
          { from: '/en/operations/table_engines/', to: '/en/engines/table-engines/' },
          { from: '/en/engines/table_engines/integrations/', to: '/en/engines/table-engines/integrations/' },
          { from: '/en/engines/table_engines/integrations/hdfs', to: '/en/engines/table-engines/integrations/hdfs' },
          { from: '/en/operations/table_engines/hdfs', to: '/en/engines/table-engines/integrations/hdfs' },
          { from: '/en/engines/table_engines/integrations/jdbc', to: '/en/engines/table-engines/integrations/jdbc' },
          { from: '/en/operations/table_engines/jdbc', to: '/en/engines/table-engines/integrations/jdbc' },
          { from: '/en/engines/table_engines/integrations/kafka', to: '/en/engines/table-engines/integrations/kafka' },
          { from: '/en/operations/table_engines/kafka', to: '/en/engines/table-engines/integrations/kafka' },
          { from: '/en/engines/table_engines/integrations/mysql', to: '/en/engines/table-engines/integrations/mysql' },
          { from: '/en/operations/table_engines/mysql', to: '/en/engines/table-engines/integrations/mysql' },
          { from: '/en/engines/table_engines/integrations/odbc', to: '/en/engines/table-engines/integrations/odbc' },
          { from: '/en/operations/table_engines/odbc', to: '/en/engines/table-engines/integrations/odbc' },
          { from: '/en/engines/table-engines/log-family/log-family', to: '/en/engines/table-engines/log-family/' },
          { from: '/en/engines/table_engines/log_family/', to: '/en/engines/table-engines/log-family/' },
          { from: '/en/engines/table_engines/log_family/log', to: '/en/engines/table-engines/log-family/log' },
          { from: '/en/operations/table_engines/log', to: '/en/engines/table-engines/log-family/log' },
          { from: '/en/engines/table_engines/log_family/stripelog', to: '/en/engines/table-engines/log-family/stripelog' },
          { from: '/en/operations/table_engines/stripelog', to: '/en/engines/table-engines/log-family/stripelog' },
          { from: '/en/engines/table_engines/log_family/tinylog', to: '/en/engines/table-engines/log-family/tinylog' },
          { from: '/en/operations/update', to: '/en/manage/updates' },
          { from: '/en/operations/table_engines/tinylog', to: '/en/engines/table-engines/log-family/tinylog' },
          { from: '/en/engines/table_engines/mergetree_family/', to: '/en/engines/table-engines/mergetree-family/' },
          { from: '/en/engines/table_engines/mergetree_family/aggregatingmergetree', to: '/en/engines/table-engines/mergetree-family/aggregatingmergetree' },
          { from: '/en/operations/table_engines/aggregatingmergetree', to: '/en/engines/table-engines/mergetree-family/aggregatingmergetree' },
          { from: '/en/engines/table_engines/mergetree_family/collapsingmergetree', to: '/en/engines/table-engines/mergetree-family/collapsingmergetree' },
          { from: '/en/operations/table_engines/collapsingmergetree', to: '/en/engines/table-engines/mergetree-family/collapsingmergetree' },
          { from: '/en/engines/table_engines/mergetree_family/custom_partitioning_key', to: '/en/engines/table-engines/mergetree-family/custom-partitioning-key' },
          { from: '/en/operations/table_engines/custom_partitioning_key', to: '/en/engines/table-engines/mergetree-family/custom-partitioning-key' },
          { from: '/en/engines/table_engines/mergetree_family/graphitemergetree', to: '/en/engines/table-engines/mergetree-family/graphitemergetree' },
          { from: '/en/operations/table_engines/graphitemergetree', to: '/en/engines/table-engines/mergetree-family/graphitemergetree' },
          { from: '/en/engines/table_engines/mergetree_family/mergetree', to: '/en/engines/table-engines/mergetree-family/mergetree' },
          { from: '/en/operations/table_engines/mergetree', to: '/en/engines/table-engines/mergetree-family/mergetree' },
          { from: '/en/engines/table_engines/mergetree_family/replacingmergetree', to: '/en/engines/table-engines/mergetree-family/replacingmergetree' },
          { from: '/en/operations/table_engines/replacingmergetree', to: '/en/engines/table-engines/mergetree-family/replacingmergetree' },
          { from: '/en/engines/table_engines/mergetree_family/replication', to: '/en/engines/table-engines/mergetree-family/replication' },
          { from: '/en/operations/table_engines/replication', to: '/en/engines/table-engines/mergetree-family/replication' },
          { from: '/en/engines/table_engines/mergetree_family/summingmergetree', to: '/en/engines/table-engines/mergetree-family/summingmergetree' },
          { from: '/en/operations/table_engines/summingmergetree', to: '/en/engines/table-engines/mergetree-family/summingmergetree' },
          { from: '/en/engines/table_engines/mergetree_family/versionedcollapsingmergetree', to: '/en/engines/table-engines/mergetree-family/versionedcollapsingmergetree' },
          { from: '/en/operations/table_engines/versionedcollapsingmergetree', to: '/en/engines/table-engines/mergetree-family/versionedcollapsingmergetree' },
          { from: '/en/engines/table_engines/special/', to: '/en/engines/table-engines/special/' },
          { from: '/en/engines/table_engines/special/buffer', to: '/en/engines/table-engines/special/buffer' },
          { from: '/en/operations/table_engines/buffer', to: '/en/engines/table-engines/special/buffer' },
          { from: '/en/engines/table_engines/special/dictionary', to: '/en/engines/table-engines/special/dictionary' },
          { from: '/en/operations/table_engines/dictionary', to: '/en/engines/table-engines/special/dictionary' },
          { from: '/en/engines/table_engines/special/distributed', to: '/en/engines/table-engines/special/distributed' },
          { from: '/en/operations/table_engines/distributed', to: '/en/engines/table-engines/special/distributed' },
          { from: '/en/engines/table_engines/special/external_data', to: '/en/engines/table-engines/special/external-data' },
          { from: '/en/operations/table_engines/external_data', to: '/en/engines/table-engines/special/external-data' },
          { from: '/en/engines/table_engines/special/file', to: '/en/engines/table-engines/special/file' },
          { from: '/en/operations/table_engines/file', to: '/en/engines/table-engines/special/file' },
          { from: '/en/engines/table_engines/special/generate', to: '/en/engines/table-engines/special/generate' },
          { from: '/en/operations/table_engines/generate', to: '/en/engines/table-engines/special/generate' },
          { from: '/en/engines/table_engines/special/join', to: '/en/engines/table-engines/special/join' },
          { from: '/en/operations/table_engines/join', to: '/en/engines/table-engines/special/join' },
          { from: '/en/engines/table_engines/special/materializedview', to: '/en/engines/table-engines/special/materializedview' },
          { from: '/en/operations/table_engines/materializedview', to: '/en/engines/table-engines/special/materializedview' },
          { from: '/en/engines/table_engines/special/memory', to: '/en/engines/table-engines/special/memory' },
          { from: '/en/operations/table_engines/memory', to: '/en/engines/table-engines/special/memory' },
          { from: '/en/engines/table_engines/special/merge', to: '/en/engines/table-engines/special/merge' },
          { from: '/en/operations/table_engines/merge', to: '/en/engines/table-engines/special/merge' },
          { from: '/en/engines/table_engines/special/null', to: '/en/engines/table-engines/special/null' },
          { from: '/en/operations/table_engines/null', to: '/en/engines/table-engines/special/null' },
          { from: '/en/engines/table_engines/special/set', to: '/en/engines/table-engines/special/set' },
          { from: '/en/operations/table_engines/set', to: '/en/engines/table-engines/special/set' },
          { from: '/en/engines/table_engines/special/url', to: '/en/engines/table-engines/special/url' },
          { from: '/en/operations/table_engines/url', to: '/en/engines/table-engines/special/url' },
          { from: '/en/engines/table_engines/special/view', to: '/en/engines/table-engines/special/view' },
          { from: '/en/operations/table_engines/view', to: '/en/engines/table-engines/special/view' },
          { from: '/en/introduction/possible_silly_questions', to: '/en/faq/general/' },
          { from: '/en/getting_started/', to: '/en/quick-start' },
          { from: '/en/getting-started/', to: '/en/quick-start' },
          { from: '/en/guides/ingest/tab_separated_values', to: '/en/getting-started/example-datasets/nypd_complaint_data' },
          { from: '/en/getting_started/example_datasets/', to: '/en/getting-started/example-datasets/' },
          { from: '/en/getting_started/example_datasets/amplab_benchmark', to: '/en/getting-started/example-datasets/amplab-benchmark' },
          { from: '/en/getting_started/example_datasets/criteo', to: '/en/getting-started/example-datasets/criteo' },
          { from: '/en/getting_started/example_datasets/metrica', to: '/en/getting-started/example-datasets/metrica' },
          { from: '/en/getting_started/example_datasets/nyc_taxi', to: '/en/getting-started/example-datasets/nyc-taxi' },
          { from: '/en/getting_started/example_datasets/ontime', to: '/en/getting-started/example-datasets/ontime' },
          { from: '/en/getting_started/example_datasets/star_schema', to: '/en/getting-started/example-datasets/star-schema' },
          { from: '/en/getting_started/example_datasets/wikistat', to: '/en/getting-started/example-datasets/wikistat' },
          { from: '/en/getting_started/install', to: '/en/install' },
          { from: '/en/operations/requirements', to: '/en/install' },
          { from: '/en/getting_started/playground', to: '/en/getting-started/playground' },
          { from: '/en/getting_started/tutorial', to: '/en/tutorial' },
          { from: '/en/guide/', to: '/en/whats-new/cloud-compatibility' },
          { from: '/en/guides/apply_catboost_model', to: '/en/sql-reference/functions/other-functions' },
          { from: '/en/guides/developer/apply-catboost-model', to: '/en/sql-reference/functions/other-functions' },
          { from: '/en/commercial/cloud', to: '/en/about-us/cloud' },
          { from: '/en/formats', to: '/en/interfaces/formats' },
          { from: '/en/formats/capnproto', to: '/en/interfaces/formats' },
          { from: '/en/formats/csv', to: '/en/interfaces/formats' },
          { from: '/en/formats/csvwithnames', to: '/en/interfaces/formats' },
          { from: '/en/formats/json', to: '/en/interfaces/formats' },
          { from: '/en/formats/jsoncompact', to: '/en/interfaces/formats' },
          { from: '/en/formats/jsoneachrow', to: '/en/interfaces/formats' },
          { from: '/en/formats/native', to: '/en/interfaces/formats' },
          { from: '/en/formats/null', to: '/en/interfaces/formats' },
          { from: '/en/formats/pretty', to: '/en/interfaces/formats' },
          { from: '/en/formats/prettycompact', to: '/en/interfaces/formats' },
          { from: '/en/formats/prettycompactmonoblock', to: '/en/interfaces/formats' },
          { from: '/en/formats/prettynoescapes', to: '/en/interfaces/formats' },
          { from: '/en/formats/prettyspace', to: '/en/interfaces/formats' },
          { from: '/en/formats/rowbinary', to: '/en/interfaces/formats' },
          { from: '/en/formats/tabseparated', to: '/en/interfaces/formats' },
          { from: '/en/formats/tabseparatedraw', to: '/en/interfaces/formats' },
          { from: '/en/formats/tabseparatedwithnames', to: '/en/interfaces/formats' },
          { from: '/en/formats/tabseparatedwithnamesandtypes', to: '/en/interfaces/formats' },
          { from: '/en/formats/tskv', to: '/en/interfaces/formats' },
          { from: '/en/formats/values', to: '/en/interfaces/formats' },
          { from: '/en/formats/vertical', to: '/en/interfaces/formats' },
          { from: '/en/formats/verticalraw', to: '/en/interfaces/formats' },
          { from: '/en/formats/xml', to: '/en/interfaces/formats' },
          { from: '/en/interfaces/http_interface', to: '/en/interfaces/http' },
          { from: '/en/interfaces/third_party/', to: '/en/interfaces/third-party/' },
          { from: '/en/interfaces/third-party/client_libraries', to: '/en/interfaces/third-party/client-libraries' },
          { from: '/en/interfaces/third-party_client_libraries', to: '/en/interfaces/third-party/client-libraries' },
          { from: '/en/interfaces/third-party_gui', to: '/en/interfaces/third-party/gui' },
          { from: '/en/introduction/distinctive_features', to: '/en/about-us/distinctive-features' },
          { from: '/en/introduction/features_considered_disadvantages', to: '/en/about-us/distinctive-features' },
          { from: '/en/introduction/ya_metrika_task', to: '/en/about-us/history' },
          { from: '/en/operations/access_rights', to: '/en/operations/access-rights' },
          { from: '/en/guides/sre/user-management/access-rights', to: '/en/operations/access-rights' },
          { from: '/en/operations/configuration_files', to: '/en/operations/configuration-files' },
          { from: '/en/operations/optimizing_performance/', to: '/en/operations/optimizing-performance/' },
          { from: '/en/operations/optimizing_performance/sampling_query_profiler', to: '/en/operations/optimizing-performance/sampling-query-profiler' },
          { from: '/en/operations/performance/sampling_query_profiler', to: '/en/operations/optimizing-performance/sampling-query-profiler' },
          { from: '/en/operations/performance_test', to: '/en/operations/performance-test' },
          { from: '/en/operations/server_configuration_parameters/', to: '/en/operations/server-configuration-parameters/' },
          { from: '/en/operations/server_settings/', to: '/en/operations/server-configuration-parameters/' },
          { from: '/en/operations/server_configuration_parameters/settings', to: '/en/operations/server-configuration-parameters/settings' },
          { from: '/en/operations/server_settings/settings', to: '/en/operations/server-configuration-parameters/settings' },
          { from: '/en/operations/settings/constraints_on_settings', to: '/en/operations/settings/constraints-on-settings' },
          { from: '/en/operations/settings/permissions_for_queries', to: '/en/operations/settings/permissions-for-queries' },
          { from: '/en/operations/settings/query_complexity', to: '/en/operations/settings/query-complexity' },
          { from: '/en/operations/settings/settings_profiles', to: '/en/operations/settings/settings-profiles' },
          { from: '/en/operations/settings/settings_users', to: '/en/operations/settings/settings-users' },
          { from: '/en/operations/system_tables', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables/system.asynchronous_metrics', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables/system.clusters', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables/system.columns', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables/system.databases', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables/system.dictionaries', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables/system.events', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables/system.functions', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables/system.merges', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables/system.metrics', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables/system.numbers', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables/system.numbers_mt', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables/system.one', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables/system.parts', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables/system.processes', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables/system.replicas', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables/system.settings', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables/system.tables', to: '/en/operations/system-tables/' },
          { from: '/en/system_tables/system.zookeeper', to: '/en/operations/system-tables/' },
          { from: '/en/operations/utils/', to: '/en/operations/utilities/' },
          { from: '/en/operations/utils/clickhouse-benchmark', to: '/en/operations/utilities/clickhouse-benchmark' },
          { from: '/en/operations/utils/clickhouse-copier', to: '/en/operations/utilities/clickhouse-copier' },
          { from: '/en/operations/utils/clickhouse-local', to: '/en/operations/utilities/clickhouse-local' },
          { from: '/en/utils', to: '/en/operations/utilities/' },
          { from: '/en/utils/clickhouse-copier', to: '/en/operations/utilities/clickhouse-copier' },
          { from: '/en/utils/clickhouse-local', to: '/en/operations/utilities/clickhouse-local' },
          { from: '/en/query_language/', to: '/en/sql-reference' },
          { from: '/en/sql_reference/', to: '/en/sql-reference' },
          { from: '/en/query_language/agg_functions/', to: '/en/sql-reference/aggregate-functions/' },
          { from: '/en/sql_reference/aggregate_functions/', to: '/en/sql-reference/aggregate-functions/' },
          { from: '/en/query_language/agg_functions/combinators', to: '/en/sql-reference/aggregate-functions/combinators' },
          { from: '/en/sql_reference/aggregate_functions/combinators', to: '/en/sql-reference/aggregate-functions/combinators' },
          { from: '/en/query_language/agg_functions/parametric_functions', to: '/en/sql-reference/aggregate-functions/parametric-functions' },
          { from: '/en/sql_reference/aggregate_functions/parametric_functions', to: '/en/sql-reference/aggregate-functions/parametric-functions' },
          { from: '/en/query_language/agg_functions/reference', to: '/en/sql-reference/aggregate-functions/reference/' },
          { from: '/en/sql_reference/aggregate_functions/reference', to: '/en/sql-reference/aggregate-functions/reference/' },
          { from: '/en/sql_reference/ansi', to: '/en/sql-reference/ansi' },
          { from: '/en/data_types/', to: '/en/sql-reference/data-types/' },
          { from: '/en/sql_reference/data_types/', to: '/en/sql-reference/data-types/' },
          { from: '/en/data_types/nested_data_structures/aggregatefunction', to: '/en/sql-reference/data-types/aggregatefunction' },
          { from: '/en/sql_reference/data_types/aggregatefunction', to: '/en/sql-reference/data-types/aggregatefunction' },
          { from: '/en/data_types/array', to: '/en/sql-reference/data-types/array' },
          { from: '/en/sql_reference/data_types/array', to: '/en/sql-reference/data-types/array' },
          { from: '/en/data_types/boolean', to: '/en/sql-reference/data-types/boolean' },
          { from: '/en/sql_reference/data_types/boolean', to: '/en/sql-reference/data-types/boolean' },
          { from: '/en/data_types/date', to: '/en/sql-reference/data-types/date' },
          { from: '/en/sql_reference/data_types/date', to: '/en/sql-reference/data-types/date' },
          { from: '/en/data_types/datetime', to: '/en/sql-reference/data-types/datetime' },
          { from: '/en/sql_reference/data_types/datetime', to: '/en/sql-reference/data-types/datetime' },
          { from: '/en/data_types/datetime64', to: '/en/sql-reference/data-types/datetime64' },
          { from: '/en/sql_reference/data_types/datetime64', to: '/en/sql-reference/data-types/datetime64' },
          { from: '/en/data_types/decimal', to: '/en/sql-reference/data-types/decimal' },
          { from: '/en/sql_reference/data_types/decimal', to: '/en/sql-reference/data-types/decimal' },
          { from: '/en/sql-reference/data-types/domains/overview', to: '/en/sql-reference/data-types/domains/' },
          { from: '/en/sql_reference/data_types/domains/', to: '/en/sql-reference/data-types/domains/' },
          { from: '/en/data_types/domains/ipv4', to: '/en/sql-reference/data-types/domains/ipv4' },
          { from: '/en/sql_reference/data_types/domains/ipv4', to: '/en/sql-reference/data-types/domains/ipv4' },
          { from: '/en/data_types/domains/ipv6', to: '/en/sql-reference/data-types/domains/ipv6' },
          { from: '/en/sql_reference/data_types/domains/ipv6', to: '/en/sql-reference/data-types/domains/ipv6' },
          { from: '/en/data_types/domains/overview', to: '/en/sql-reference/data-types/domains/' },
          { from: '/en/sql_reference/data_types/domains/overview', to: '/en/sql-reference/data-types/domains/' },
          { from: '/en/data_types/enum', to: '/en/sql-reference/data-types/enum' },
          { from: '/en/sql_reference/data_types/enum', to: '/en/sql-reference/data-types/enum' },
          { from: '/en/data_types/fixedstring', to: '/en/sql-reference/data-types/fixedstring' },
          { from: '/en/sql_reference/data_types/fixedstring', to: '/en/sql-reference/data-types/fixedstring' },
          { from: '/en/data_types/float', to: '/en/sql-reference/data-types/float' },
          { from: '/en/sql_reference/data_types/float', to: '/en/sql-reference/data-types/float' },
          { from: '/en/data_types/int_uint', to: '/en/sql-reference/data-types/int-uint' },
          { from: '/en/sql_reference/data_types/int_uint', to: '/en/sql-reference/data-types/int-uint' },
          { from: '/en/data_types/nested_data_structures/', to: '/en/sql-reference/data-types/nested-data-structures/' },
          { from: '/en/sql_reference/data_types/nested_data_structures/', to: '/en/sql-reference/data-types/nested-data-structures/' },
          { from: '/en/data_types/nested_data_structures/nested', to: '/en/sql-reference/data-types/nested-data-structures/nested' },
          { from: '/en/sql_reference/data_types/nested_data_structures/nested', to: '/en/sql-reference/data-types/nested-data-structures/nested' },
          { from: '/en/data_types/nullable', to: '/en/sql-reference/data-types/nullable' },
          { from: '/en/sql_reference/data_types/nullable', to: '/en/sql-reference/data-types/nullable' },
          { from: '/en/sql_reference/data_types/simpleaggregatefunction', to: '/en/sql-reference/data-types/simpleaggregatefunction' },
          { from: '/en/data_types/special_data_types/', to: '/en/sql-reference/data-types/special-data-types/' },
          { from: '/en/sql_reference/data_types/special_data_types/', to: '/en/sql-reference/data-types/special-data-types/' },
          { from: '/en/data_types/special_data_types/expression', to: '/en/sql-reference/data-types/special-data-types/expression' },
          { from: '/en/sql_reference/data_types/special_data_types/expression', to: '/en/sql-reference/data-types/special-data-types/expression' },
          { from: '/en/data_types/special_data_types/interval', to: '/en/sql-reference/data-types/special-data-types/interval' },
          { from: '/en/sql_reference/data_types/special_data_types/interval', to: '/en/sql-reference/data-types/special-data-types/interval' },
          { from: '/en/data_types/special_data_types/nothing', to: '/en/sql-reference/data-types/special-data-types/nothing' },
          { from: '/en/sql_reference/data_types/special_data_types/nothing', to: '/en/sql-reference/data-types/special-data-types/nothing' },
          { from: '/en/data_types/special_data_types/set', to: '/en/sql-reference/data-types/special-data-types/set' },
          { from: '/en/sql_reference/data_types/special_data_types/set', to: '/en/sql-reference/data-types/special-data-types/set' },
          { from: '/en/data_types/string', to: '/en/sql-reference/data-types/string' },
          { from: '/en/sql_reference/data_types/string', to: '/en/sql-reference/data-types/string' },
          { from: '/en/data_types/tuple', to: '/en/sql-reference/data-types/tuple' },
          { from: '/en/sql_reference/data_types/tuple', to: '/en/sql-reference/data-types/tuple' },
          { from: '/en/data_types/uuid', to: '/en/sql-reference/data-types/uuid' },
          { from: '/en/sql_reference/data_types/uuid', to: '/en/sql-reference/data-types/uuid' },
          { from: '/en/query_language/dicts/', to: '/en/sql-reference/dictionaries/' },
          { from: '/en/sql_reference/dictionaries/', to: '/en/sql-reference/dictionaries/' },
          { from: '/en/sql_reference/dictionaries/external_dictionaries/', to: '/en/sql-reference/dictionaries/external-dictionaries' },
          { from: '/en/query_language/dicts/external_dicts', to: '/en/sql-reference/dictionaries/external-dictionaries/external-dicts' },
          { from: '/en/sql_reference/dictionaries/external_dictionaries/external_dicts', to: '/en/sql-reference/dictionaries/external-dictionaries/external-dicts' },
          { from: '/en/query_language/dicts/external_dicts_dict', to: '/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict' },
          { from: '/en/sql_reference/dictionaries/external_dictionaries/external_dicts_dict', to: '/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict' },
          { from: '/en/query_language/dicts/external_dicts_dict_hierarchical', to: '/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-hierarchical' },
          { from: '/en/sql_reference/dictionaries/external_dictionaries/external_dicts_dict_hierarchical', to: '/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-hierarchical' },
          { from: '/en/query_language/dicts/external_dicts_dict_layout', to: '/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-layout' },
          { from: '/en/sql_reference/dictionaries/external_dictionaries/external_dicts_dict_layout', to: '/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-layout' },
          { from: '/en/query_language/dicts/external_dicts_dict_lifetime', to: '/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-lifetime' },
          { from: '/en/sql_reference/dictionaries/external_dictionaries/external_dicts_dict_lifetime', to: '/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-lifetime' },
          { from: '/en/query_language/dicts/external_dicts_dict_sources', to: '/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-sources' },
          { from: '/en/sql_reference/dictionaries/external_dictionaries/external_dicts_dict_sources', to: '/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-sources' },
          { from: '/en/query_language/dicts/external_dicts_dict_structure', to: '/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-structure' },
          { from: '/en/sql_reference/dictionaries/external_dictionaries/external_dicts_dict_structure', to: '/en/sql-reference/dictionaries/external-dictionaries/external-dicts-dict-structure' },
          { from: '/en/query_language/dicts/internal_dicts', to: '/en/sql-reference/dictionaries/internal-dicts' },
          { from: '/en/sql_reference/dictionaries/internal_dicts', to: '/en/sql-reference/dictionaries/internal-dicts' },
          { from: '/en/query_language/functions/', to: '/en/sql-reference/functions/' },
          { from: '/en/sql_reference/functions/', to: '/en/sql-reference/functions/' },
          { from: '/en/query_language/functions/arithmetic_functions', to: '/en/sql-reference/functions/arithmetic-functions' },
          { from: '/en/sql_reference/functions/arithmetic_functions', to: '/en/sql-reference/functions/arithmetic-functions' },
          { from: '/en/query_language/functions/array_functions', to: '/en/sql-reference/functions/array-functions' },
          { from: '/en/sql_reference/functions/array_functions', to: '/en/sql-reference/functions/array-functions' },
          { from: '/en/query_language/functions/array_join', to: '/en/sql-reference/functions/array-join' },
          { from: '/en/sql_reference/functions/array_join', to: '/en/sql-reference/functions/array-join' },
          { from: '/en/query_language/functions/bit_functions', to: '/en/sql-reference/functions/bit-functions' },
          { from: '/en/sql_reference/functions/bit_functions', to: '/en/sql-reference/functions/bit-functions' },
          { from: '/en/query_language/functions/bitmap_functions', to: '/en/sql-reference/functions/bitmap-functions' },
          { from: '/en/sql_reference/functions/bitmap_functions', to: '/en/sql-reference/functions/bitmap-functions' },
          { from: '/en/query_language/functions/comparison_functions', to: '/en/sql-reference/functions/comparison-functions' },
          { from: '/en/sql_reference/functions/comparison_functions', to: '/en/sql-reference/functions/comparison-functions' },
          { from: '/en/query_language/functions/conditional_functions', to: '/en/sql-reference/functions/conditional-functions' },
          { from: '/en/sql_reference/functions/conditional_functions', to: '/en/sql-reference/functions/conditional-functions' },
          { from: '/en/query_language/functions/date_time_functions', to: '/en/sql-reference/functions/date-time-functions' },
          { from: '/en/sql_reference/functions/date_time_functions', to: '/en/sql-reference/functions/date-time-functions' },
          { from: '/en/query_language/functions/encoding_functions', to: '/en/sql-reference/functions/encoding-functions' },
          { from: '/en/sql_reference/functions/encoding_functions', to: '/en/sql-reference/functions/encoding-functions' },
          { from: '/en/query_language/functions/ext_dict_functions', to: '/en/sql-reference/functions/ext-dict-functions' },
          { from: '/en/sql_reference/functions/ext_dict_functions', to: '/en/sql-reference/functions/ext-dict-functions' },
          { from: '/en/query_language/functions/functions_for_nulls', to: '/en/sql-reference/functions/functions-for-nulls' },
          { from: '/en/sql_reference/functions/functions_for_nulls', to: '/en/sql-reference/functions/functions-for-nulls' },
          { from: '/en/query_language/functions/geo', to: '/en/sql-reference/functions/geo/' },
          { from: '/en/sql_reference/functions/geo', to: '/en/sql-reference/functions/geo/' },
          { from: '/en/query_language/functions/hash_functions', to: '/en/sql-reference/functions/hash-functions' },
          { from: '/en/sql_reference/functions/hash_functions', to: '/en/sql-reference/functions/hash-functions' },
          { from: '/en/query_language/functions/in_functions', to: '/en/sql-reference/functions/in-functions' },
          { from: '/en/sql_reference/functions/in_functions', to: '/en/sql-reference/functions/in-functions' },
          { from: '/en/query_language/functions/introspection', to: '/en/sql-reference/functions/introspection' },
          { from: '/en/sql_reference/functions/introspection', to: '/en/sql-reference/functions/introspection' },
          { from: '/en/query_language/functions/ip_address_functions', to: '/en/sql-reference/functions/ip-address-functions' },
          { from: '/en/sql_reference/functions/ip_address_functions', to: '/en/sql-reference/functions/ip-address-functions' },
          { from: '/en/query_language/functions/json_functions', to: '/en/sql-reference/functions/json-functions' },
          { from: '/en/sql_reference/functions/json_functions', to: '/en/sql-reference/functions/json-functions' },
          { from: '/en/query_language/functions/logical_functions', to: '/en/sql-reference/functions/logical-functions' },
          { from: '/en/sql_reference/functions/logical_functions', to: '/en/sql-reference/functions/logical-functions' },
          { from: '/en/query_language/functions/machine_learning_functions', to: '/en/sql-reference/functions/machine-learning-functions' },
          { from: '/en/sql_reference/functions/machine_learning_functions', to: '/en/sql-reference/functions/machine-learning-functions' },
          { from: '/en/query_language/functions/math_functions', to: '/en/sql-reference/functions/math-functions' },
          { from: '/en/sql_reference/functions/math_functions', to: '/en/sql-reference/functions/math-functions' },
          { from: '/en/query_language/functions/other_functions', to: '/en/sql-reference/functions/other-functions' },
          { from: '/en/sql_reference/functions/other_functions', to: '/en/sql-reference/functions/other-functions' },
          { from: '/en/query_language/functions/random_functions', to: '/en/sql-reference/functions/random-functions' },
          { from: '/en/sql_reference/functions/random_functions', to: '/en/sql-reference/functions/random-functions' },
          { from: '/en/query_language/functions/rounding_functions', to: '/en/sql-reference/functions/rounding-functions' },
          { from: '/en/sql_reference/functions/rounding_functions', to: '/en/sql-reference/functions/rounding-functions' },
          { from: '/en/query_language/functions/splitting_merging_functions', to: '/en/sql-reference/functions/splitting-merging-functions' },
          { from: '/en/sql_reference/functions/splitting_merging_functions', to: '/en/sql-reference/functions/splitting-merging-functions' },
          { from: '/en/query_language/functions/string_functions', to: '/en/sql-reference/functions/string-functions' },
          { from: '/en/sql_reference/functions/string_functions', to: '/en/sql-reference/functions/string-functions' },
          { from: '/en/query_language/functions/string_replace_functions', to: '/en/sql-reference/functions/string-replace-functions' },
          { from: '/en/sql_reference/functions/string_replace_functions', to: '/en/sql-reference/functions/string-replace-functions' },
          { from: '/en/query_language/functions/string_search_functions', to: '/en/sql-reference/functions/string-search-functions' },
          { from: '/en/sql_reference/functions/string_search_functions', to: '/en/sql-reference/functions/string-search-functions' },
          { from: '/en/query_language/functions/type_conversion_functions', to: '/en/sql-reference/functions/type-conversion-functions' },
          { from: '/en/sql_reference/functions/type_conversion_functions', to: '/en/sql-reference/functions/type-conversion-functions' },
          { from: '/en/query_language/functions/url_functions', to: '/en/sql-reference/functions/url-functions' },
          { from: '/en/sql_reference/functions/url_functions', to: '/en/sql-reference/functions/url-functions' },
          { from: '/en/query_language/functions/uuid_functions', to: '/en/sql-reference/functions/uuid-functions' },
          { from: '/en/sql_reference/functions/uuid_functions', to: '/en/sql-reference/functions/uuid-functions' },
          { from: '/en/query_language/functions/ym_dict_functions', to: '/en/sql-reference/functions/ym-dict-functions' },
          { from: '/en/sql_reference/functions/ym_dict_functions', to: '/en/sql-reference/functions/ym-dict-functions' },
          { from: '/en/query_language/operators', to: '/en/sql-reference/operators/' },
          { from: '/en/sql_reference/operators', to: '/en/sql-reference/operators/' },
          { from: '/en/sql_reference/statements/', to: '/en/sql-reference/statements/' },
          { from: '/en/query_language/alter', to: '/en/sql-reference/statements/alter/' },
          { from: '/en/sql_reference/statements/alter', to: '/en/sql-reference/statements/alter/' },
          { from: '/en/query_language/create', to: '/en/sql-reference/statements/create/' },
          { from: '/en/sql_reference/statements/create', to: '/en/sql-reference/statements/create/' },
          { from: '/en/query_language/insert_into', to: '/en/sql-reference/statements/insert-into' },
          { from: '/en/sql_reference/statements/insert_into', to: '/en/sql-reference/statements/insert-into' },
          { from: '/en/query_language/misc', to: '/en/sql-reference/statements/' },
          { from: '/en/sql-reference/statements/misc', to: '/en/sql-reference/statements/' },
          { from: '/en/sql_reference/statements/misc', to: '/en/sql-reference/statements/' },
          { from: '/en/query_language/select', to: '/en/sql-reference/statements/select/' },
          { from: '/en/sql_reference/statements/select', to: '/en/sql-reference/statements/select/' },
          { from: '/en/query_language/show', to: '/en/sql-reference/statements/show' },
          { from: '/en/sql_reference/statements/show', to: '/en/sql-reference/statements/show' },
          { from: '/en/query_language/system', to: '/en/sql-reference/statements/system' },
          { from: '/en/sql_reference/statements/system', to: '/en/sql-reference/statements/system' },
          { from: '/en/query_language/syntax', to: '/en/sql-reference/syntax' },
          { from: '/en/sql_reference/syntax', to: '/en/sql-reference/syntax' },
          { from: '/en/query_language/table_functions/', to: '/en/sql-reference/table-functions/' },
          { from: '/en/sql_reference/table_functions/', to: '/en/sql-reference/table-functions/' },
          { from: '/en/query_language/table_functions/file', to: '/en/sql-reference/table-functions/file' },
          { from: '/en/sql_reference/table_functions/file', to: '/en/sql-reference/table-functions/file' },
          { from: '/en/query_language/table_functions/generate', to: '/en/sql-reference/table-functions/generate' },
          { from: '/en/sql_reference/table_functions/generate', to: '/en/sql-reference/table-functions/generate' },
          { from: '/en/query_language/table_functions/hdfs', to: '/en/sql-reference/table-functions/hdfs' },
          { from: '/en/sql_reference/table_functions/hdfs', to: '/en/sql-reference/table-functions/hdfs' },
          { from: '/en/query_language/table_functions/input', to: '/en/sql-reference/table-functions/input' },
          { from: '/en/sql_reference/table_functions/input', to: '/en/sql-reference/table-functions/input' },
          { from: '/en/query_language/table_functions/jdbc', to: '/en/sql-reference/table-functions/jdbc' },
          { from: '/en/sql_reference/table_functions/jdbc', to: '/en/sql-reference/table-functions/jdbc' },
          { from: '/en/query_language/table_functions/merge', to: '/en/sql-reference/table-functions/merge' },
          { from: '/en/sql_reference/table_functions/merge', to: '/en/sql-reference/table-functions/merge' },
          { from: '/en/query_language/table_functions/mysql', to: '/en/sql-reference/table-functions/mysql' },
          { from: '/en/sql_reference/table_functions/mysql', to: '/en/sql-reference/table-functions/mysql' },
          { from: '/en/query_language/table_functions/numbers', to: '/en/sql-reference/table-functions/numbers' },
          { from: '/en/sql_reference/table_functions/numbers', to: '/en/sql-reference/table-functions/numbers' },
          { from: '/en/query_language/table_functions/odbc', to: '/en/sql-reference/table-functions/odbc' },
          { from: '/en/sql_reference/table_functions/odbc', to: '/en/sql-reference/table-functions/odbc' },
          { from: '/en/query_language/table_functions/remote', to: '/en/sql-reference/table-functions/remote' },
          { from: '/en/sql_reference/table_functions/remote', to: '/en/sql-reference/table-functions/remote' },
          { from: '/en/query_language/table_functions/url', to: '/en/sql-reference/table-functions/url' },
          { from: '/en/sql_reference/table_functions/url', to: '/en/sql-reference/table-functions/url' },
          { from: '/en/whats_new/', to: '/en/whats-new' },
          { from: '/en/changelog/', to: '/en/whats-new/changelog/' },
          { from: '/en/whats_new/changelog/', to: '/en/whats-new/changelog/' },
          { from: '/en/changelog/2017', to: '/en/whats-new/changelog/2017' },
          { from: '/en/whats_new/changelog/2017', to: '/en/whats-new/changelog/2017' },
          { from: '/en/changelog/2018', to: '/en/whats-new/changelog/2018' },
          { from: '/en/whats_new/changelog/2018', to: '/en/whats-new/changelog/2018' },
          { from: '/en/changelog/2019', to: '/en/whats-new/changelog/2019' },
          { from: '/en/whats_new/changelog/2019', to: '/en/whats-new/changelog/2019' },
          { from: '/en/extended_roadmap', to: '/en/whats-new/roadmap' },
          { from: '/en/roadmap', to: '/en/whats-new/roadmap' },
          { from: '/en/whats_new/roadmap', to: '/en/whats-new/roadmap' },
          { from: '/en/security_changelog', to: '/en/whats-new/security-changelog' },
          { from: '/en/whats_new/security_changelog', to: '/en/whats-new/security-changelog' },
          { from: '/en/introduction/', to: '/en/intro' },
          { from: '/en/introduction/adopters', to: '/en/about-us/adopters' },
          { from: '/en/introduction/distinctive-features', to: '/en/about-us/distinctive-features' },
          { from: '/en/introduction/history', to: '/en/about-us/history' },
          { from: '/en/introduction/performance', to: '/en/about-us/performance' },
          { from: '/en/', to: '/en/home' },
          { from: '/', to: '/en/home' },
          { from: '/en/getting-started/tutorial', to: '/en/tutorial' },
          { from: '/en/getting-started/install', to: '/en/install' },
          { from: '/quick-start', to: '/en/quick-start' },
          { from: '/ru/whats-new/index', to: '/ru/whats-new/' },
          { from: '/en/operations', to: '/en/manage' },
          { from: '/en/operations/backup', to: '/en/manage/backups' },
          { from: '/manage/security', to: '/en/manage/security' },
        ],
      },
    ]
  ],
};

module.exports = config;
