/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  english: [
    'en/intro',
    'en/quick-start',
    'en/tutorial',
    {
      type: 'category',
      label: 'Example Datasets',
      link: {
        type: 'generated-index',
        slug: '/en/getting-started/example-datasets'
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'en/getting-started/example-datasets',
        },
        {
          type: 'link',
          label: 'NYPD Complaint Data',
          href: '/en/guides/ingest/tab_separated_values',
        }
      ]
    },
    {
      type: 'category',
      label: 'Integrations',
      link: {
        type: 'generated-index',
        slug: '/en/integrations'
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'en/integrations',
        }
      ]
    },
    {
      type: 'category',
      label: 'Connect a UI',
      link: {
        type: 'generated-index',
        slug: '/en/connect-a-ui'
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'en/connect-a-ui',
        }
      ]
    },
    {
     type: 'category',
     label: 'User Guides',
     link: {
       type: 'generated-index',
       slug: '/en/guides'
     },
     collapsed: true,
     items: [
       {
        type: 'autogenerated',
        dirName: 'en/guides',
       }
     ]
    },   
    {
      type: 'category',
      label: 'Reference',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        {
         type: 'category',
         label: 'Getting Started',
         link: {
           type: 'generated-index',
           slug: 'en/getting-started'
         },
         collapsed: true,
         collapsible: true,
         items: [
           {
             type: 'doc',
             id: 'en/getting-started/install',
           },
           {
             type: 'doc',
             id: 'en/getting-started/playground',
           },
         ],
        },
        {
          type: 'category',
          label: 'Interfaces',
          link: {
            type: 'generated-index',
            slug: 'en/interfaces'
          },
          collapsed: true,
          collapsible: true,
          items: [
           {
            type: 'autogenerated',
            dirName: 'en/interfaces',
           }
          ]  
         },
         {
          type: 'category',
          label: 'Engines',
          link: {
            type: 'generated-index',
            slug: 'en/engines'
          },
          collapsed: true,
          collapsible: true,
          items: [
           {
            type: 'autogenerated',
            dirName: 'en/engines',
           }
          ]  
         },
         {
          type: 'category',
          label: 'SQL Reference',
          link: {
            type: 'generated-index',
            slug: 'en/sql-reference'
          },
          collapsed: true,
          collapsible: true,
          items: [
           {
            type: 'autogenerated',
            dirName: 'en/sql-reference',
           }
          ]  
         },
         {
          type: 'category',
          label: 'Operations',
          link: {
            type: 'generated-index',
            slug: 'en/operations'
          },
          collapsed: true,
          collapsible: true,
          items: [
           {
            type: 'autogenerated',
            dirName: 'en/operations',
           }
          ]  
         },
         {
          type: 'category',
          label: 'Development',
          link: {
            type: 'generated-index',
            slug: 'en/development'
          },
          collapsed: true,
          collapsible: true,
          items: [
           {
            type: 'autogenerated',
            dirName: 'en/development',
           },
          ]  
         },

         
       ]
     },
    {
      type: 'category',
      label: 'Native protocol',
      link: {
        type: 'generated-index',
        slug: 'en/native-protocol'
      },
      collapsed: true,
      collapsible: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'en/native-protocol',
        }
      ]
    },
     {
       type: 'category',
       label: 'FAQ',
       link: {
         type: 'generated-index',
         slug: '/en/faq',
       },
       collapsed: true,
       items: [
         {
          type: 'autogenerated',
          dirName: 'en/faq',
         }
       ]
      },
      {
        type: 'category',
        label: "What's New",
        link: {
          type: 'generated-index',
          slug: '/en/whats-new',
        },
        collapsed: true,
        items: [
          {
           type: 'autogenerated',
           dirName: 'en/whats-new',
          }
        ]
       },
       {
        type: 'category',
        label: 'About Us',
        link: {
          type: 'generated-index',
          slug: '/en/about-us',
        },
        collapsed: true,
        items: [
          {
           type: 'autogenerated',
           dirName: 'en/about-us',
          }
        ]
       },
      ], 
   russia: [
     {
       type: 'autogenerated',
       dirName: 'ru',
      },
    ],
    chinese: [
      {
        type: 'autogenerated',
        dirName: 'zh',
       },
     ],
 };

module.exports = sidebars;
