#!/usr/bin/env python3
"""Sync ClickStack OTel schema CREATE TABLE statements from upstream HyperDX
into AUTOGENERATED blocks in the docs.

Each block in the docs page is shaped like:

    <!--AUTOGENERATED_START-->
    <!-- sync-clickstack-schema: id=<table_name> source=<raw URL> -->
    ```sql
    CREATE TABLE ... ${DATABASE}.<table_name> ( ... );
    ```
    <!--AUTOGENERATED_END-->

The script fetches each `source`, extracts the CREATE TABLE matching `id`,
and rewrites the SQL block. Upstream variable placeholders like ${DATABASE}
and ${TABLES_TTL} are preserved verbatim.

Exit code is always 0; the GitHub workflow detects changes via `git diff`.
"""

from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

TARGETS = [
    REPO_ROOT
    / "docs/use-cases/observability/clickstack/ingesting-data/schemas.md",
]

BLOCK_RE = re.compile(
    r"<!--AUTOGENERATED_START-->\n"
    r"<!-- sync-clickstack-schema: id=(?P<id>\S+) source=(?P<source>\S+) -->\n"
    r"```sql\n(?P<body>.*?)\n```\n"
    r"<!--AUTOGENERATED_END-->",
    re.DOTALL,
)


def fetch_text(url: str) -> str:
    with urllib.request.urlopen(url, timeout=30) as resp:
        return resp.read().decode("utf-8")


def extract_create_table(sql: str, table_id: str) -> str:
    cleaned = "\n".join(
        line for line in sql.splitlines() if not re.match(r"--\s*\+goose\b", line)
    )
    pattern = re.compile(
        r"CREATE TABLE(?:\s+IF NOT EXISTS)?\s+\$\{DATABASE\}\."
        + re.escape(table_id)
        + r"\b.*?;",
        re.DOTALL,
    )
    match = pattern.search(cleaned)
    if not match:
        raise RuntimeError(f'Could not find CREATE TABLE for id="{table_id}"')
    return match.group(0).strip()


def sync_file(path: Path) -> bool:
    original = path.read_text(encoding="utf-8")
    blocks = list(BLOCK_RE.finditer(original))
    if not blocks:
        print(f"[skip] no AUTOGENERATED ClickStack blocks in {path}")
        return False

    source_cache: dict[str, str] = {}
    updated = original
    for block in blocks:
        table_id = block.group("id")
        source = block.group("source")
        if source not in source_cache:
            print(f"  fetching {source}")
            source_cache[source] = fetch_text(source)
        new_create = extract_create_table(source_cache[source], table_id)
        replacement = (
            "<!--AUTOGENERATED_START-->\n"
            f"<!-- sync-clickstack-schema: id={table_id} source={source} -->\n"
            "```sql\n"
            f"{new_create}\n"
            "```\n"
            "<!--AUTOGENERATED_END-->"
        )
        updated = updated.replace(block.group(0), replacement)

    if updated == original:
        print(f"[unchanged] {path}")
        return False

    path.write_text(updated, encoding="utf-8")
    print(f"[updated]   {path}")
    return True


def main() -> int:
    any_changed = False
    for target in TARGETS:
        if sync_file(target):
            any_changed = True
    print("done" + (" (changes detected)" if any_changed else " (no changes)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())