name: Update Algolia Search

on:
  pull_request:
    types:
      - closed

  workflow_dispatch:
  
  schedule:
    - cron: '0 4 * * *'

env:
  PYTHONUNBUFFERED: 1 # Force the stdout and stderr streams to be unbuffered

jobs:
  update-search:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'update search') && github.event.pull_request.base.ref == 'main')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Run Prep from Master
        run: yarn copy-clickhouse-repo-docs

      - name: Run Auto Generate Settings
        run: yarn autogenerate-settings

      - name: Run Indexer
        run: yarn run-indexer
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_APP_ID: 5H9UG7CX5W

      - name: Verify Completion
        run: echo "All steps completed successfully!"
