# This workflow uses the method described at:
# https://vercel.com/docs/concepts/deployments/deploy-hooks
#
# In the `on:` section a schedule is set to catch any merged docs
# in the ClickHouse/ClickHouse repo. 
#
# To use from control-plane or ClickHouse/ClickHouse repos
# just add the final `step` "Trigger build of docs website"
# to a CI job in control-plane or ClickHouse/ClickHouse
#
# If this needs to be used in any other repos contact the folks
# in #security-access-request
#
# There is also a workflow_dispatch, which means you can trigger
# the workflow from the GitHub Actions page.
 
name: Trigger docs website build on schedule
on: 
  schedule:
    - cron: '10 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Trigger production build in Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build of docs website
        run: curl -X POST ${{ secrets.VERCEL_DOC_BUILD }}
