name: Playwright + Argos Tests

on:
  # Trigger on deployment event
  deployment_status:
  workflow_dispatch:
  # Trigger when a label is added to a PR
  pull_request:
    types:
      - labeled

jobs:
  test:
    # Run tests only if the deployment is successful
    if: |
      (
        github.event_name == 'deployment_status' &&
        github.event.deployment_status.state == 'success' &&
        contains(github.event.deployment_status.deployment.payload.pull_request.labels.*.name, 'visual-test')
      ) || (
        github.event_name == 'pull_request' &&
        github.event.action == 'labeled' &&
        github.event.label.name == 'visual-test'
      )
    runs-on: ubuntu-latest

    steps:

      # Step 1: Check out the repository
      - name: Check out docs repo
        uses: actions/checkout@v4
        with:
          repository: ClickHouse/clickhouse-docs
          path: ./

      - name: Fetch pull request labels
        if: github.event_name == 'deployment_status'
        id: fetch-labels
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.deployment_status.deployment.payload.pull_request.number
            });
            core.setOutput('labels', JSON.stringify(pr.data.labels));

      # Step 3: Check for "visual-test" label
      - name: Check for "visual-test" label
        id: label-check
        run: |
          echo "Checking for 'visual-test' label..."
          echo "${{ steps.fetch-labels.outputs.labels }}" | jq '.[].name' | grep -q 'visual-test' && echo "true" || echo "false"
        shell: bash
        env:
          LABELS: ${{ steps.fetch-labels.outputs.labels }}
      
      - name: Log BASE_URL
        run: echo "BASE_URL=${{ github.event.deployment_status.environment_url }}"
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}